### ISSUE TITLE
-makePurchase:withDiscount:completionBlock: finishes with error for subscribed users

### ISSUE THREAD

**Issue by mikejd** [RevenueCat/purchases-ios#100]
Hello,

Let's say a user has an active subscription to product X and redeems an [offer](https://developer.apple.com/app-store/subscriptions/#subscription-offers) for the same product. The operation is successful according to Apple, which is indicated by "You're all set" popup. However, we receive transaction with state `.failed` along with some generic error in `-makePurchase:withDiscount:completionBlock:` callback in this case. Also no changes in RevenueCat dashboard nor in decoded receipt are observed immediately after that.

Is it intended behaviour, a bug in RevenueCat or some glitch in Apple sandbox?

**Comment by jeiting** [comment]
Hey mike!

So this is just a quirk of sandbox. Crossgrades of an active subscription have never worked properly on Sandbox and they actually still don’t with offers.

However, you should still be able to rest offers with a lapsed subscription. So, once the account has one completed cycle in that product, it should work.

We just shipped offers support yesterday so let us know if you run into anything weird!

**Comment by mikejd** [comment]
Hi Jacob, thanks for reply!

> So this is just a quirk of sandbox. Crossgrades of an active subscription have never worked properly on Sandbox and they actually still don’t with offers.

Yeah, these issues look similar. Do you know if cross-grades work OK in production?

If I got it right from the docs and dev forums, user is charged immediately in case of same duration cross-grade, so I assume we can expect successful transaction. Is it the case from you experience?

**Comment by jeiting** [comment]
Yeah, crossgrades work fine on production. 

You might want to check out my old blog post on this:
https://medium.com/revenuecat-blog/ios-subscription-groups-explained-8c5b8325d4ab

How a user is charged depends on a bunch of factors.
