### ISSUE TITLE
Remove the build step that checks TARGET_OS macro in Swift files

### ISSUE THREAD

**Issue by Juanpe** [RevenueCat/purchases-ios#1011]
During the Swift migration, we created a new build phase to validate that some macros, like TARGET_OS_ (TARGET_OS_IPHONE, TARGET_OS_SIMULATOR), are not included in any Swift file. I think this script is no longer needed since there is no ObjC code in the project. 

![Screenshot 2021-12-01 at 10 15 49](https://user-images.githubusercontent.com/1409041/144206235-bf31787c-b919-43bb-9797-a3b3f2822c16.png)

- **Issue:** #629
- **PR:** #655 

WDYT? I could remove it 🙂

**Comment by aboedo** [comment]
Oh, yeah, totally! I saw it the other day and forgot to add a ticket for it, but it's no longer necessary since this was only useful when we still had objc files around, so we have no need for `TARGET_OS` anywhere. 
Thanks for reporting!

**Comment by Juanpe** [comment]
Great! I have a branch ready that includes this change, but I've seen that you've self-assigned it, do you want to do it yourself or can I open the PR?

**Comment by aboedo** [comment]
Shoot, I self-assigned out of habit just for replying to the ticket 😂 It's all yours! I'll assign you
