### ISSUE TITLE
Allow to delete the current "purchases" instance

### ISSUE THREAD

**Issue by enricenrich** [RevenueCat/purchases-ios#102]
Have an option in the SDK to delete / stop the current active instance of `Purchases`. 

It can be useful in cases where the user signs out and you don't want to use an anonymous app user ID.

**Comment by aboedo** [comment]
Thanks for the suggestion. We're going to consider this feature, since it may be useful for some folks. It's not trivial because there might be implications to existing transactions in the queue, though, and to purchases that happen directly from App Store. I'm closing this issue for now.
