### ISSUE TITLE
CircleCI `runtest` does not parse test results

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1025]
<img width="542" alt="Screen Shot 2021-12-02 at 12 52 04" src="https://user-images.githubusercontent.com/685609/144501106-a0a76ec8-b3cc-4ccb-9a2f-8f0445ae2518.png">

I've tried several things in [this branch](https://github.com/RevenueCat/purchases-ios/tree/circle-ci-test-reports), but ultimately it seems like it just doesn't support having multiple files in inside of `fastlane/test_output` (see [test output](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios?branch=circle-ci-test-reports)):

<img width="552" alt="Screen Shot 2021-12-02 at 12 53 13" src="https://user-images.githubusercontent.com/685609/144501252-fc4ff44f-7071-4019-ae0e-badd3018a0d4.png">

The last thing I haven't considered yet is to make change our `fastlane test` to only generate one of these.

**Comment by taquitos** [comment]
Just casually tagging in @joshdholtz, wondering it's an outstanding issue in trainer.

**Comment by NachoSoto** [comment]
I was gonna say that this isn't `trainer`'s fault, but I just noticed that for integration tests, which do get parsed by CircleCI, we don't use `trainer`.

**Comment by joshdholtz** [comment]
👇 It shows that it was uploaded so maybe there is an error with the parsing of the junit xml (?????) Might be good to try to run the xml file through a validator of some sort 🤷‍♂️ 

<img width="1029" alt="Screen Shot 2021-12-03 at 12 15 25 PM" src="https://user-images.githubusercontent.com/401294/144652514-4a1d2fc0-a23d-4aed-91bf-62c903c7ef88.png">

**Comment by NachoSoto** [comment]
I'm an idiot, I was changing the wrong `CircleCI` job. `runtest` doesn't actually have `store_test_results`!
Fixing...

**Comment by NachoSoto** [comment]
Fixed! 
https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4339/workflows/f84cb4bd-fdf1-47f0-89a8-26622457ce30/jobs/12887/tests

**Comment by joshdholtz** [comment]
Teamwork 💪
