### ISSUE TITLE
Optimize `receiptHasTransactions` using StoreKit 2

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#1037]
We check whether a receipt has transactions in order to decide whether to post it to the backend under certain circumstances: 
https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Purchasing/PurchasesOrchestrator.swift#L555

This isn't perfect, since the local receipt might not have transactions, but a purchase could still have happened. 

This could be optimized on iOS 15+ (and equivalent) devices, by checking existing purchases using StoreKit 2. For StoreKit 2-compatible devices, we can use [`Transaction.all`](https://developer.apple.com/documentation/storekit/transaction/3851203-all), which should be up-to-date, and thus more precise than checking for the receipt. 

We should have a new method `customerHasTransactions` (ideally in a new class) that decides depending on the OS version, whether to use the StoreKit 1 or the StoreKit 2 approach, and returns `true` if there has been at least one transaction, `false` otherwise. 

https://app.shortcut.com/revenuecat/story/11648/leverage-storekit-2-for-receipthastransactions

**Comment by Juanpe** [comment]
Hi! I could do it 🙂

**Comment by aboedo** [comment]
@Juanpe all yours!!! Thanks for offering! 🙌🙌

**Comment by Juanpe** [comment]
I've created a PR with a proposal. Sorry for the delay but I don't have too much experience with async/await and it took me longer than I thought at first :)
