### ISSUE TITLE
Change async methods to support iOS 13.0 / macOS 10.15 / tvOS 13 / watchOS 6

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1052]
With Xcode 13.2: "you can now use Swift Concurrency in applications that deploy to macOS 10.15, iOS 13, tvOS 13, and watchOS 6 or newer. This support includes async/await, actors, global actors, structured concurrency, and the task APIs."

**Comment by Juanpe** [comment]
Hi @NachoSoto, I've opened a PR updating the availability 👍🏼
