### ISSUE TITLE
Move discount logic from Purchases to a new class

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1055]
Extracted subtask from #848.

> `Purchases.swift` should be as thin and light as possible

- [setting up a `payment` and starting a purchase with the `payment`](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Public/Purchases.swift#L944)
- [determining which SK version to use for a given `StoreProduct`, then creating a `payment` for it](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Public/Purchases.swift#L996).

> We'll have to have different logic for both SK versions, and we'll eventually want to also add support for the `quantity` field in `SKPayment` (and its equivalent for SK2), so moving those responsibilities into a different class will make things easier to maintain in the long run

**Comment by aboedo** [comment]
@NachoSoto this is fixed, right?

**Comment by NachoSoto** [comment]
Yeah I think we can close this now, no more purchasing logic in Purchases.
