### ISSUE TITLE
Unable to run cocoapods with Purchases pods

### ISSUE THREAD

**Issue by pradeepb28** [RevenueCat/purchases-ios#1063]
- [X] I have updated Purchases SDK to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [X ] I have searched the [Community](https://community.revenuecat.com)
- [ X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
I've tried to run cocoapods  but it says unable to find Purchases
Here is how I included in the file
```
pod 'Purchases', :git => "https://github.com/RevenueCat/purchases-ios.git"
```

Output
![CleanShot 2021-12-13 at 13 29 54](https://user-images.githubusercontent.com/6823101/145774192-655833f5-7847-44fd-8edb-10a26fe65b3c.png)

1. Environment
   1. Platform: iOS
   2. SDK version: n/a
   3. OS version: 11.3.1
   4. Xcode version: n/a
   5. How widespread is the issue. Percentage of devices affected: n/a
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by pradeepb28** [comment]
Also I've tried
```
 Pod Purchases
```

but I get this error
![CleanShot 2021-12-13 at 13 41 02](https://user-images.githubusercontent.com/6823101/145775333-c3393e1b-e2f3-4710-a376-7f0adce3dc6a.png)

**Comment by aboedo** [comment]
Hi @pradeepb28! 👋 Thanks for reporting! 

This is expected, here's what's going on: 
- We're working on a brand new version of the SDK, fully re-written in Swift, which also includes a few new features. This new version has a **renamed pod** in Cocoapods, called `RevenueCat`. 
- The new version is currently in beta, which is why in our docs we have setup instructions for the currently-stable version, called `Purchases`. 
- If you'd like to use the latest stable version, you can just set up the line _without_ pointing to the github repo: 
```ruby
pod 'Purchases'
```
- When you point to the github repo, Cocoapods will read off the default branch (`main`) and won't see a spec for `Purchases`, it'll only see one for `RevenueCat`, i.e.: our V4 SDK that was renamed.
- If you'd like to give the beta a try, you can also do: 
```ruby
pod 'RevenueCat', :git => "https://github.com/RevenueCat/purchases-ios.git"
```

Here's the list [of everything that's changed in our V4 SDK](https://github.com/RevenueCat/purchases-ios/blob/main/docs/V4_API_Updates.md), currently in beta.

**Comment by pradeepb28** [comment]
@aboedo I tried 
```
pod 'Purchases'
```

but I am still facing the below issue
![CleanShot 2021-12-13 at 18 05 39](https://user-images.githubusercontent.com/6823101/145813443-e6e1b8a0-c098-40fc-9e0d-f0c5a0a77344.png)

MacOS: 11.3.1 (M1 machine)
Pod version: 1.10.2

**Comment by aboedo** [comment]
🤔 
I just tried this on a brand new project and had no issues with the following podfile: 

```ruby
target 'testCocoapods (iOS)' do
  use_frameworks!
  pod 'Purchases'
end

target 'testCocoapods (macOS)' do
  use_frameworks!
  pod 'Purchases'
end
```

@pradeepb28 I'm running Cocoapods `1.11.2`. Perhaps updating your Cocoapods version solves the issue?

**Comment by pradeepb28** [comment]
still no luck @aboedo is there any chance I can point to the git url. This is the only I was able to solve other pods in my file.
I tried the git url under purchases-ios but it didnt worked(as per my original issue)

**Comment by aboedo** [comment]
@pradeepb28 is there anything more in the output other than what you pasted above? Anything before "oh no, an error occurred"? 

I wonder if there might be an issue with targeted architectures or deployment targets, could you share details about which architectures your app is targeting, as well as deployment targets for them? 

You can still point to the github url:

### For the stable version, v3: 

```ruby
pod 'Purchases', :git => 'https://github.com/RevenueCat/purchases-ios.git', :tag => '3.13.1'
```

Keep in mind that if you go with this path, you'd have to update the `tag` whenever you want to update to a newer version fo the SDK to get bug fixes or new features. 

### For the beta version, v4 [(keep in mind the API updates)](https://github.com/RevenueCat/purchases-ios/blob/main/docs/V4_API_Updates.md):

```
pod 'RevenueCat', :git => "https://github.com/RevenueCat/purchases-ios.git"
```

**Comment by pradeepb28** [comment]
This is what is in podfile @aboedo 
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bird search' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
platform :ios, '15.0'

  # Pods for Bird_search
pod 'RevealingSplashView', :git => "https://github.com/PiXeL16/RevealingSplashView.git"
pod 'Mixpanel-swift', :git => "https://github.com/mixpanel/mixpanel-swift.git"
pod 'SwiftDate', :git => "https://github.com/malcommac/SwiftDate.git"
pod 'Purchases'

end
```

Output attached here
[Terminal Saved Output.zip](https://github.com/RevenueCat/purchases-ios/files/7704369/Terminal.Saved.Output.zip)

**Comment by aboedo** [comment]
Thanks for sharing! I think you're experiencing [this issue](https://github.com/CocoaPods/CocoaPods/issues/10518). 

It seems to be an incompatibility issue with a ruby gem called `ffi`, there's [a suggested workaround here](https://github.com/CocoaPods/CocoaPods/issues/10518#issuecomment-798912624). 

There are a few other possible solutions there. Would you mind giving them a shot?

**Comment by pradeepb28** [comment]
@aboedo it worked, finally I can give a shot on RevenueCat

**Comment by aboedo** [comment]
Glad it's working! Let us know if you run into more issues. Have a great day!
