### ISSUE TITLE
Malformed Backend Data that cannot be instantiated into CustomerInfo or Subscriber Data objects

### ISSUE THREAD

**Issue by winstondu** [RevenueCat/purchases-ios#1096]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
RevenueCat's backend seems to send malformed data that the ios-sdk cannot parse into a CustomerInfo object. This is an issue for a significant number of our users (hovering around 1%). In our app's case, because we need to retrieve data from RevenueCat to log the user in to app (so we know the user has the feature entitlements), this is effectively leading to a lot of user frustration that they cannot interact with our app.

We have an ongoing forum discussion issue here, where @taquitos  has been replying: https://community.revenuecat.com/sdks-51/randomly-and-false-zero-entitlements-returned-from-purchaseproduct-withcompletion-657?postid=2197#post2197

Our logs show a lot of "😿‼️ Unable to instantiate SubscriberData from json object" errors, as well as "Attempt to update CustomerInfo from network failed.
Received malformed response from the backend."

** General Information**

1. Environment
   1. Platform: iOS
   2. SDK version: 4.0.0-beta-7.0
   3. OS version: iOS 15.2
   4. Xcode version: 13.2
   5. How widespread is the issue. Percentage of devices affected. (1%+ of devices)
   
2. Debug log:
 😿‼️ Unable to instantiate SubscriberData from json object:
["management_url": <null>, "subscriptions": {
}, "original_purchase_date": <null>, "first_seen": 2021-12-16T23:11:47Z, "last_seen": 2021-12-16T23:11:47Z, "non_subscriptions": {
}, "original_app_user_id": $RCAnonymousID:82e86fa9c880495184a4bcd6feb4478c, "entitlements": {
}, "original_application_version": <null>, "other_purchases": {
}]

3. Steps to reproduce, with a description of expected vs. actual behavior: **Unclear, as it only affects some users**

**Things the RevenueCat team can do**
Put up some test code in this repository where I can input the problematic json as a string, so as to track down what exactly in the json is failing to be parsed.

**Comment by winstondu** [comment]
Additional logging to help debug this was merged in https://github.com/RevenueCat/purchases-ios/pull/1095

**Comment by taquitos** [comment]
I've got a Draft PR up (not merging it) that exposes the creation of `CustomerInfo` through `Purchases` with this API:
`@objc public func parseCustomerInfo(fromJSONString json: String) -> CustomerInfo {`
You can see how it's used in the test: https://github.com/RevenueCat/purchases-ios/pull/1097/files#diff-0fe20160d5c535102ea28e6a4e437993244c8da6ffa0c36f11887ee3c3604589

I'd recommend using SPM and pointing it to the PR branch-> `test_string`, then running your app with the new RevenueCat SDK and attempting to load the json there. That way you have all your dependencies loaded up just like they would be in production.

**Comment by winstondu** [comment]
@taquitos , thank you. After further investigation and testing with our affected users, it seemed that these users may have had an unconventional date/calendar system and as a result the dateformatter didn't parse the backend response date string. Moreover, it appears that #998 (not in 4.0.0-beta-7) somehow fixes this issue.

For now, we are cherrypicking #998 and using that for our pod. If you can get a release out soon with that change (but without the other changes since 4.0.0-beta-7), that would probably be extremely helpful for the community.

I will confirm that it is a fix later today and close this issue.

**Comment by NachoSoto** [comment]
Oh that's a great find! Probably the old formatter implicitly used the device's locale but the new one doesn't. I'll see if I can write a test tomorrow to make sure this doesn't break again.

**Comment by NachoSoto** [comment]
@winstondu do you happen to know which locales were failing? I haven't been able to reproduce this after reverting #998, but I'd like to add a failing test to make sure this never breaks again.

**Comment by winstondu** [comment]
Fix Confirmed. Closed

**Comment by winstondu** [comment]
> @winstondu do you happen to know which locales were failing? I haven't been able to reproduce this after reverting #998, but I'd like to add a failing test to make sure this never breaks again.

We were trying to reproduce this ourselves, but we don't have that particular piece of info. Our user came from mexico city though.

In any case, your original code was
```
    static let iso8601SecondsDateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
        return dateFormatter
    }()
```

The correct formulation should be:
```
static let iso8601SecondsDateFormatter: DateFormatter = {
    let iso8601Formatter = DateFormatter()
    iso8601Formatter.calendar = Calendar(identifier: .iso8601)
    iso8601Formatter.locale = Locale(identifier: "en_US_POSIX") // this is crucial
    iso8601Formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
    iso8601Formatter.timeZone = TimeZone(secondsFromGMT: 0) // this is crucial as well.
    return iso8601Formatter
}()
```


Take a look at:
https://stackoverflow.com/questions/50586855/date-from-server-in-swift

**Comment by NachoSoto** [comment]
Yeah that makes sense. Luckily `ISO8601DateFormatter` handles that automatically. 
Tests unfortunately still passed with different locales and regions:
![Screen Shot 2021-12-20 at 10 34 32](https://user-images.githubusercontent.com/685609/146815978-60955aa5-bb40-427e-bef8-12df9a531738.png)

But Xcode's Test Plans don't allow overriding timezones or calendar, which is likely what broke the old implementation.

I think this is safe to close now though considering we're using `ISO8601DateFormatter` everywhere.
Thanks a lot for helping us track this down 🙏
