### ISSUE TITLE
Lint `PurchasesTests`

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1104]
Currently the `PurchasesTests` directory is excluded in `.swiftlint.yml`. Test code is production code so I think it would be a good idea to lint that as well, and fix any failures (which are a ton currently).

**Comment by Juanpe** [comment]
Hi :wave: Yesterday I started to fix this issue but it will take me a couple of days.

BTW, I'll ask you when I finish silencing all errors and warnings because there might be too many modified files and we'll have to decide if I should open more than one PR, ok?

**Comment by aboedo** [comment]
Sounds good! When you have it ready, we can take a look at the diff and decide on single PR vs multiple, trying to optimize for the smoothest path to merging. Thanks for taking care of it!!
