### ISSUE TITLE
`PurchasesOrchestrator.purchase(package:completion:)` assumes that `purchase(sk2Product:)` throws `StoreKitError`

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1114]
If `purchase(sk2Product:)` fails because of an error when posting the receipt, the Error can be something like `ErrorCode.invalidReceiptError`, but the method calls `ErrorUtils.purchasesError(withStoreKitError:)`, which ends up returning `ErrorCode.unknownError` instead.

_Nacho cries in un-typed `Error`s_

**Comment by Juanpe** [comment]
Hi @NachoSoto! 👋🏼 I could do it if it's still free

**Comment by NachoSoto** [comment]
Go for it!
