### ISSUE TITLE
EXC_BAD_ACCESS RCDeviceCache.m:168 (updateAllCachesIfNeeded)

### ISSUE THREAD

**Issue by Bathilde** [RevenueCat/purchases-ios#1122]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

1. Environment
   1. Platform: iOS
   2. SDK version: 3.13.1
   3. OS version: 15
   4. Xcode version: 13

I have several users on Bugsnag having a crash on RCDeviceCache. This case happens all the time when the app is relaunch from background mode.

[On iOS 15, the application now has a pre-warm up step.](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence) In my case, I had to move all sdk initialization to the viewDidLoad of my first displayed UIViewController. It seems that when the application is coming back from the background mode, the sdk auto-reload the data.
However, since the app is not "warmup", UserDefaults are not available leading to a crash

I did not find any track of similar issues on the github

You can find the full stacktrace here:
```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x64695f6e68.  
0  libobjc.A.dylib     _class_getMethodImplementation 
1  Foundation          __NSKVONotifyingOriginalClassForIsa 
2  Foundation          __NSKeyValueObservationInfoGetObservances 
3  Foundation          -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] 
4  Foundation          -[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] 
5  CoreFoundation      -[CFPrefsSource forEachObserver:] 
6  CoreFoundation      -[CFPrefsSource _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] 
7  CoreFoundation      ____CFPrefsDeliverPendingKVONotificationsGuts_block_invoke 
8  CoreFoundation      ___CFDictionaryApplyFunction_block_invoke 
9  CoreFoundation      _CFBasicHashApply 
10 CoreFoundation      _CFDictionaryApplyFunction 
11 CoreFoundation      __CFPrefsDeliverPendingKVONotificationsGuts 
12 CoreFoundation      -[_CFXPreferences _deliverPendingKVONotifications] 
13 CoreFoundation      ___108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke 
14 CoreFoundation      _normalizeQuintuplet 
15 CoreFoundation      -[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:] 
16 CoreFoundation      -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]
17 CoreFoundation      __CFPreferencesSetAppValueWithContainerAndConfiguration 
18 Foundation          -[NSUserDefaults(NSUserDefaults) setObject:forKey:] 
19 FastingForWoman     -[RCDeviceCache setPurchaserInfoCacheTimestamp:forAppUserID:] (RCDeviceCache.m:168:5) 
20 FastingForWoman     -[RCDeviceCache setPurchaserInfoCacheTimestampToNowForAppUserID:] (RCDeviceCache.m:163:5) 
21 FastingForWoman     -[RCPurchaserInfoManager fetchAndCachePurchaserInfoWithAppUserID:isAppBackgrounded:completion:] (RCPurchaserInfoManager.m:97:5) 
22 FastingForWoman     -[RCPurchaserInfoManager fetchAndCachePurchaserInfoIfStaleWithAppUserID:isAppBackgrounded:completion:] (RCPurchaserInfoManager.m:129:9)
23 FastingForWoman     __38-[RCPurchases updateAllCachesIfNeeded]_block_invoke (RCPurchases.m:923:9) 
24 libdispatch.dylib   __dispatch_call_block_and_release 
25 libdispatch.dylib   __dispatch_client_callout 
26 libdispatch.dylib   __dispatch_main_queue_callback_4CF 
27 CoreFoundation      ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ 
28 CoreFoundation      ___CFRunLoopRun 
29 CoreFoundation      _CFRunLoopRunSpecific 
30 GraphicsServices    _GSEventRunModal 
31 UIKitCore           -[UIApplication _run] 
32 UIKitCore           _UIApplicationMain 
33 libswiftUIKit.dylib UIApplicationMain(_:_:_:_:)

```

If there is a method that can be called on the `func applicationWillEnterForeground(_ application: UIApplication)` function, let me know !

**Comment by aboedo** [comment]
hi @Bathilde! You should be able to safely call the SDK initialization code in [`application(_:didFinishLaunchingWithOptions:)
`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application) instead, since at the time of that call, `NSUserDefaults` will already be ready to use. 

Hope this helps!

**Comment by Bathilde** [comment]
Thank you for your answer, but when I had the call on the `didFinishLaunchingWithOptions`, I had a very problematic number of crash also coming from call on UserDefaults. It seems that this is the case since the app is compatible with iOS15

**Comment by NachoSoto** [comment]
Out of curiosity, are you seeing crashes from users running iOS 15.1 and 15.2 as well? I've seen issues regarding iOS pre-warm up behavior that got fixed in 15.2.

**Comment by NachoSoto** [comment]
To add some more context here too: Apple documentation says that `didFinishLaunchingWithOptions` isn't called during 
pre-warming, but it totally is. Source: https://twitter.com/felixomni/status/1466140731324739592?s=21

**Comment by Bathilde** [comment]
I can see issue on users running iOS 15.0, 15.0.2, 15.1 and 15.2

My last guess is that RevenueCat is using UserDefaults the same time as my code (even if UserDefaults is threadsafe), so I will probably try to move the part a bit after mid-january. I'll let you know if that change anything

**Comment by aboedo** [comment]
@Bathilde sounds good, please let us know how it goes!

**Comment by Bathilde** [comment]
@aboedo of course I'll let you know!

In the mean time, if you see a way for me to disable the auto-refresh of the cash when app is relaunch, that could be nice. My crash-free user number is falling to 95% because of the RCDeviceCache crash

**Comment by aboedo** [comment]
@Bathilde workarounds will depend on the exact source of the problem: 
- if the problem is that NSUserDefaults is getting used before being ready (i.e.: the iOS change in behavior with the bug that Nacho mentioned), then the solution would be to move the setup code so that it executes a little later in the app flow, when NSUserDefaults is guaranteed to be working. It should still be done early so that the SDK catches any updates to the payment queue, though. 
- if the problem is something else, then, we should dig into what it is and come with an appropriate solution. 
Are you observing changes to userDefaults by any chance? From the stacktrace, it kinda looks like when the SDK stores the value for `purchaserInfoCacheTimestamp`, the crash happens when a KVO callback gets triggered. Maybe there's an observer that's been de-referenced?

**Comment by Bathilde** [comment]
I found a legacy listener on UserDefaults that was linked to a viewController. I'm removing it and i'll let you know if that change anything on the prod version. As stated in my initial message, the crash is happening when coming back from background mode. It can make sense that the viewController does not exist and then break the call to UserDefaults.

Thank you for you help !

**Comment by aboedo** [comment]
@Bathilde that's great!! 😃 Hope that works! Keep us posted!

**Comment by Bathilde** [comment]
No more crash since the legacy listerner was removed.

Thank you for all your help !
