### ISSUE TITLE
RevenueCat not working on macOS

### ISSUE THREAD

**Issue by Daniyaldehleh** [RevenueCat/purchases-ios#1179]
- [X ] I have updated Purchases SDK to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [X ] I have searched the [Community](https://community.revenuecat.com)
- [ X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

Per your [document](https://docs.revenuecat.com/docs/getting-started-1#7-configure-the-purchases-sdk) You've to use:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
  
    Purchases.logLevel = .debug
    Purchases.configure(withAPIKey: "public_sdk_key")
  
}
```
for macOS apps too. However, that can only work when you import UiKit which that's for IOS not MacOS. Thus, would like to know what's the alternative to that for macOS apps.

**Comment by NachoSoto** [comment]
Thanks for the bug report! What error do you get when you don't `import UIKit`?

**Comment by aboedo** [comment]
@Daniyaldehleh Thanks for reporting!!

Yeah, this is an issue with our docs. [`application:didFinishLaunchingWithOptions:`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application?language=objc#) is not compatible with macOS, since it does reference `UIApplication`, which is a part of `UIKit`. 

The equivalent for macOS is [`applicationDidFinishLaunching`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428385-applicationdidfinishlaunching?language=objc#). 

We'll get the docs updated, thanks!

**Comment by Daniyaldehleh** [comment]
Hi @aboedo & @NachoSoto! Thanks for the update. I still see `UIApplication` in the doc which I believe is not compatible with macOS app. I've replaced it with: `NSApplicationDelegate` so feel free to use my code in your doc.

Nonetheless, I am still struggling to make revenueCat work with my macOS app where despite doing everything right (https://gist.github.com/Daniyaldehleh/974037d3cc346b5809cc26211e356467), I get:
`
<PurchaserInfo
 originalApplicationVersion: (null),
 latestExpirationDate: (null)
 activeEntitlements: {
},
 activeSubscriptions: {
},
 nonConsumablePurchases: {(
)},
 requestDate: 2022-01-17 20:28:35 +0000
firstSeen: 2022-01-16 06:34:46 +0000,
originalAppUserId: $RCAnonymousID:25c74f2b440b49baba60bebf92f7eb85,
entitlements: {
},
>
<RCEntitlementInfos: self.all={
}, self.active={
}>
`
from print(info) & not entitlement as empty. My dashboard is already completely setup per the app store IDs.

**Comment by codykerns** [comment]
Closing as this seems to be related to #1180 and so we'll keep discussion there.
