### ISSUE TITLE
Entitlements empty despite product existing

### ISSUE THREAD

**Issue by Daniyaldehleh** [RevenueCat/purchases-ios#1180]
- [X] I have updated Purchases SDK to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [ X] I have searched the [Community](https://community.revenuecat.com)
- [ X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

Hi @aboedo & @NachoSoto! Thanks for the update. I still see `UIApplication` in the doc which I believe is not compatible with macOS app. I've replaced it with: `NSApplicationDelegate` so feel free to use my code in your doc.

Nonetheless, I am still struggling to make revenueCat work with my macOS app where despite doing everything right (https://gist.github.com/Daniyaldehleh/974037d3cc346b5809cc26211e356467), I get:
```
<PurchaserInfo
 originalApplicationVersion: (null),
 latestExpirationDate: (null)
 activeEntitlements: {
},
 activeSubscriptions: {
},
 nonConsumablePurchases: {(
)},
 requestDate: 2022-01-17 20:28:35 +0000
firstSeen: 2022-01-16 06:34:46 +0000,
originalAppUserId: $RCAnonymousID:25c74f2b440b49baba60bebf92f7eb85,
entitlements: {
},
>
<RCEntitlementInfos: self.all={
}, self.active={
}>
```
from print(info) & not entitlement as empty. My dashboard is already completely setup per the app store IDs.

despite `print(offerings.current)` showing:
```
Optional(<Offering {
	identifier=12 Months BeTimeful Pro Access
	serverDescription=12 Months Annual BeTimeful Membership
	availablePackages=(
    "<RCPackage: 0x600001e14390>"
)
	lifetime=(null)
	annual=<RCPackage: 0x600001e14390>
	sixMonth=(null)
	threeMonth=(null)
	twoMonth=(null)
	monthly=(null)
	weekly=(null)
}>)
```

1. Environment
   1. Platform: macOS
   2. SDK version: 3.0.0
   3. OS version: BigSur
   4. Xcode version: 12

**Comment by NachoSoto** [comment]
I imagine it might be a typo, but can you confirm you're using the latest 3.x version of the SDK and not 3.0.0?

**Comment by Daniyaldehleh** [comment]
using: pod 'Purchases', '~> 3.13.2'

same problem occuring

**Comment by aboedo** [comment]
Hi! I tagged our support team who'll be better-equipped to help you get set up, as this looks like a configuration issue. 

In the meantime, though, I'd point out a couple of things to look out for in the code you shared: 
- [`NSApplicationDelegate`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate?language=objc#) doesn't have a method called `application:didFinishLaunchingWithOptions:`, so simply replacing `UIApplication` with `NSApplication` in `application:didFinishLaunchingWithOptions:` won't work, the method won't be called. Instead, the `configure` code should be in `applicationDidFinishLaunching:`, which is a part of `NSApplicationDelegate`. 
- `configure` should only happen once in an app's lifecycle, calling it multiple times could cause issues. 
- Perhaps there's something in the debug logs that might point to specific configuration issues? 
- [This guide](https://community.revenuecat.com/sdks-51/why-are-offerings-or-products-empty-124)  might be able to help you with the most common configuration issues. 
- [Our community](https://community.revenuecat.com) is the best place to get help in getting set up. 

Hope this helps!

**Comment by Daniyaldehleh** [comment]
Hey! I tried applicationdidfinishlaunching but can't get a call back in the view controller method in macOS after the applicationdidfinishlaunching method is called in the appdelegate and my Revenuecat instance is configureg before i setup in view controller.

```
@main
class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ notification: Notification) {
        print("calledFailed to set (contentViewController) user defined inspected property on (NSWindow): There is no singleton instance.")
        Purchases.configure(withAPIKey: "")


    }
class ViewController: NSViewController, WKNavigationDelegate {

  override func viewDidLoad() {

    super.viewDidLoad()


    setup()
  }
```

**Comment by taquitos** [comment]
Closing since this seems like it's resolved, feel free to reopen and drop a comment if that's not correct 🚀

**Comment by Daniyaldehleh** [comment]
Hi Cody!
Thanks for helping out. Right now the only problem is that I keep on getting:
`[Purchases] - ERROR: 😿‼️ The receipt is not valid.`
every time I hit subscribe despite following every step that I followed for building it for IOS & it works on IOS.

**Comment by aboedo** [comment]
@Daniyaldehleh thanks for the update! I replied to the `receipt is not valid` issue here https://github.com/RevenueCat/purchases-ios/issues/1256#issuecomment-1031522453, let's continue the discussion there 👍
