### ISSUE TITLE
4.0.0-rc.1: warning with file Documentation.docc

### ISSUE THREAD

**Issue by Timac** [RevenueCat/purchases-ios#1228]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
After upgrading from 4.0.0-beta.10 to 4.0.0-rc.1, I see a warning in Xcode 13.2.1 (13C100) when using purchases-is as a Swift Package:

```
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/timac/Library/Developer/Xcode/DerivedData/xxxxx/SourcePackages/checkouts/purchases-ios/Documentation.docc
```

**Environment**
   1. Platform: iOS
   2. SDK version: 4.0.0-rc.1
   3. OS version: iOS 15.0
   4. Xcode version: 13.2.1 (13C100)

**Steps to reproduce**
- Create a new Xcode project with Xcode 13.2.1
- Add RevenueCat with SPM to your iOS project with the url `https://github.com/RevenueCat/purchases-ios.git` and exact version `4.0.0-rc.1`
- Build the project

Result: You see a warning 

```
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/timac/Library/Developer/Xcode/DerivedData/xxxxx/SourcePackages/checkouts/purchases-ios/Documentation.docc
```

<img width="1051" alt="screenshot" src="https://user-images.githubusercontent.com/738543/151609848-770557c2-6659-4c04-9cf0-a206b544b6c9.png">

Expected Result: You shouldn't see a warning.

**Additional context**

The issue couldn't be seen with 4.0.0-beta.10 on the same machine with the same setup

**Comment by aboedo** [comment]
Hi @Timac! Thanks for reporting! 
We actually found this too and fixed it in https://github.com/RevenueCat/purchases-ios/pull/1227, it'll be fixed by the next release 🙌

**Comment by Timac** [comment]
Awesome! Sorry I did not see this commit
