### ISSUE TITLE
Another IAP API - App Store Review 

### ISSUE THREAD

**Issue by WayneEld** [RevenueCat/purchases-ios#124]
Hi Guys

I have been using revenue cat on my MacOS app Shepherd for a couple of weeks now.  Things were up and running. After updating the app with a bug fix (not related to purchases), I received this message from app rejecting the app.

"Your app enables the purchase of content, services, or functionality by means other than the in-app purchase (IAP) API.

We noticed that your app or its metadata provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines."

Is this related to revenue cat's version not been updated to the latest version in line with Apples IAP API?
Have you encountered this before?
Is this perhaps a classic app store review that is misunderstood?

Your help will be appreciated.

I am currently using revenue cat for MacOS Version 2.3.

**Comment by rkotzy** [comment]
Usually that message is if you have messaging or a link to purchase content outside of your app. Are you using Stripe or any other payment gateways besides IAP? Did they include a screenshot?

**Comment by WayneEld** [comment]
You are 100% correct. There was a browser link to FAQs and a help guide on the app's website. From there you could further find an older link to pricing that was not the same as the stated price. It was a static older price. (not stating the tiers per Apple's and further Revenue Cat's API). Thanks for the help.
