### ISSUE TITLE
Apple App store - sandboxing doc for macOS outdated?

### ISSUE THREAD

**Issue by Daniyaldehleh** [RevenueCat/purchases-ios#1256]
Hi there,

I've specifically updated my mac from Big Sur to Monetery (12.2) to be able to sandbox test with revenue cat. According to your doc(https://docs.revenuecat.com/docs/apple-app-store#add-the-sandbox-test-account-to-your-device) to sandbox user on mac you've to:

> On macOS 11.5.2 or greater, navigate to App Store > Preferences > Sandbox Account.

<img width="1103" alt="Screen Shot 2022-02-04 at 1 08 13 PM" src="https://user-images.githubusercontent.com/58639693/152580571-041ced36-2784-4a81-bc0a-e36094541e7d.png">

but such option doesn't seem to appear on when you go to Preferences.

I'd also like to know if setting:

`Purchases.logLevel = .debug`

in delegate, automatically makes me a sandbox user & won't charge me as a temporary solution.

**Comment by aboedo** [comment]
hi! 

The option will show up after you make your first sandbox purchase. 
So basically, run your app, make a purchase, and you'll get prompted for sandbox credentials. From that moment on, the option will show up in App Store -> Preferences on that computer. 

> I'd also like to know if setting:
> Purchases.logLevel = .debug
> in delegate, automatically makes me a sandbox user & won't charge me as a temporary solution.

Those are separate concepts. The `logLevel` just controls how much information is output to the logs you can see in Xcode's pane at the bottom. 

Being a sandbox user / getting charged depends on where the app you're running was built from: if you're installing it from Xcode, or the build was made with Xcode, it'll go to the Sandbox environment, and you won't get charged. If you distribute it through TestFlight, it'll also go through Sandbox and you won't get charged. 

The only way you will actually get charged is if you install through App Store (or other means of installing if you're on macOS). 

Hope this helps!

**Comment by Daniyaldehleh** [comment]
Got it!
Also, I've implemented revenueCat on IOS & it works perfectly. I copy pasted every code & step for mac & I keep on hitting:
`[Purchases] - ERROR: 😿‼️ The receipt is not valid.`
despite literally taking every step that I took for IOS. Hence, Idk if this is a revenueCat mac specific problem?

**Comment by aboedo** [comment]
@Daniyaldehleh if things are working correctly, you should feel free to disregard that error. 

That error is output while trying to locally parse the receipt, but there are scenarios where that parsing doesn't work yet (like when using storekit config files).

However, local receipt parsing is only used for mild optimization in some features, so even if receipt parsing fails, the SDK will continue to work and let our servers handle receipts. 

I realize that the message is confusing, though, so I'll make a note to make it clearer or remove it. 

Let us know if you run into any more issues!

**Comment by Daniyaldehleh** [comment]
Hi Aboedo!
Thanks for bringing this to my attention!
I'm afraid that the actual transaction doesn't go through cause unlike with the IOS where once transaction is made, the customers goes under sandbox users, it doesn't happen with macOS. 
Hence, I am afraid that we don't end up charging the customer in prod mode as well.
Here's the gist file if you'd like to double check my code as well based on your tutorial that I've followed.

**Comment by aboedo** [comment]
@Daniyaldehleh the code looks good at a glance. 
Purchases behave the same way on iOS and macOS, so if one of them is working correctly and the other one isn't, things point to a configuration error. 

Could you provide more information about what's happening exactly? I.e.: does the macOS purchase go through correctly, getting to the "you're all set" message? 
Could you share debug logs for the case where the entitlement isn't granted on macOS?

**Comment by Daniyaldehleh** [comment]
https://user-images.githubusercontent.com/58639693/152847379-06de1975-456f-4945-9e8d-eb6297bb01ae.mov

**Comment by Daniyaldehleh** [comment]
Could you please let me know how I can prevent entitlement from being granted to share you the logs?

**Comment by aboedo** [comment]
🤔 I'm surprised that we don't see more detail in the logs. Have you set `logLevel = .error` or otherwise a customer log handler for our SDK? If so, could you set it to `.debug` and then share the logs? 
Does the purchase show up in the dashboard if you click on "show sandbox data"?

**Comment by Daniyaldehleh** [comment]
I'd like to sincerely apologize for forgetting to turn on debug mode. 
I'm still struggling to find how to reset the app to make purchase happen from beginning for you to see the errors. I've done this before by deleting the app from my mac but it no longer shows for it to be deleted. 

Please let me know if this video gives you the insight that you need.

https://user-images.githubusercontent.com/58639693/152851647-4e4dbe48-3aca-46f0-9935-cfdf71a864f3.mov

**Comment by Daniyaldehleh** [comment]
I'd like to sincerely apologize for forgetting to turn on debug mode.
Here's the video:

**Comment by Daniyaldehleh** [comment]
I believe this video makes it super clear:
https://user-images.githubusercontent.com/58639693/152852259-00685538-33b6-479e-a09a-59e3e416ad58.mov

**Comment by Daniyaldehleh** [comment]
I believe this video makes it super clear:

https://user-images.githubusercontent.com/58639693/152852334-2f4217d2-10fb-42c4-9932-b00c760baab6.mov

**Comment by Daniyaldehleh** [comment]
```
[Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: BeTimeful_59.88_1Y_1w0 3 ((null)) (null) - 1
2022-02-07 13:48:47.833789-0500 BeTimeful[1953:21063] [Purchases] - DEBUG: ℹ️ Loaded receipt from url Contents/_MASReceipt/receipt -- file:///Users/daniyaldehleh/Library/Developer/Xcode/DerivedData/BeTimefulSafari3-cryuivktttyogyejpndbamqtifqq/Build/Products/Debug/BeTimeful.app/
2022-02-07 13:48:47.833962-0500 BeTimeful[1953:20035] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: $RCAnonymousID:aa4a103e51de49bab5fdeda8181d87dc
2022-02-07 13:48:47.834857-0500 BeTimeful[1953:20035] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /receipts
2022-02-07 13:48:47.834937-0500 BeTimeful[1953:20035] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
2022-02-07 13:48:48.085523-0500 BeTimeful[1953:21060] [Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 304
2022-02-07 13:48:48.085981-0500 BeTimeful[1953:21060] [Purchases] - ERROR: 😿‼️ The receipt is not valid.
2022-02-07 13:48:48.086152-0500 BeTimeful[1953:21060] [Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
2022-02-07 13:48:48.086188-0500 BeTimeful[1953:20035] [Purchases] - DEBUG: 💰 Finishing transaction BeTimeful_59.88_1Y_1w0 3 ((null))
2022-02-07 13:48:48.116381-0500 BeTimeful[1953:21063] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: BeTimeful_59.88_1Y_1w0 3 ((null) (null)) (null) - 1
```

**Comment by Daniyaldehleh** [comment]
so I am not sure if something is wrong on my side or revenueCat

**Comment by codykerns** [comment]
Hey @Daniyaldehleh!

Are you using StoreKit Config files to test in-app purchases, or are you using real products set up in App Store Connect?

**Comment by Daniyaldehleh** [comment]
Hi @codykerns !
The product is approved from app store & configuration.storekit for product to be identified. Please do let me know if this answers your question.
![Screen Shot 2022-02-07 at 5 45 14 PM](https://user-images.githubusercontent.com/58639693/152884940-4a7aea0a-95cf-432e-a240-60aea6971c39.png)
![Screen Shot 2022-02-07 at 5 45 36 PM](https://user-images.githubusercontent.com/58639693/152884964-1585e24a-8df9-4147-96f2-dfbea1b5157d.png)

**Comment by Daniyaldehleh** [comment]
I was also [told](https://github.com/RevenueCat/purchases-ios/issues/1256#issuecomment-1030255803) that once you make your first sandbox purchase you can switch to a sandbox user by going to the preferences of mac store but that doesn't seem to be the case.

**Comment by codykerns** [comment]
Hey @Daniyaldehleh,

StoreKit config files aren't currently supported for macOS, which is likely the issue here. Can you disable the StoreKit configuration file in your scheme, then try re-running the app and provide us a copy of full debug logs here to investigate further if you're still encountering an error?

**Comment by aboedo** [comment]
> I was also told that once you make your first sandbox purchase you can switch to a sandbox user by going to the preferences of mac store but that doesn't seem to be the case.

That's my bad: it does show up, but only if the purchase is made _without_ StoreKit configuration files. When you use StoreKit Configuration files, your app runs in a different environment that isn't Sandbox (you won't get charged, but it's technically a different _kind_ of sandbox environment) and thus doesn't use Sandbox accounts.

**Comment by Daniyaldehleh** [comment]
Hi @codykerns !

i removed storeKit configuration file as reference & I am afraid it still didn't change anything:


https://user-images.githubusercontent.com/58639693/153017592-6499d804-4a4f-4a95-806e-a2d166f9efd2.mov

```
Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: BeTimeful_59.88_1Y_1w0 3 ((null)) (null) - 1
2022-02-08 10:19:49.046918-0500 BeTimeful[2022:19671] [Purchases] - DEBUG: ℹ️ Loaded receipt from url Contents/_MASReceipt/receipt -- file:///Users/daniyaldehleh/Library/Developer/Xcode/DerivedData/BeTimefulSafari3-cryuivktttyogyejpndbamqtifqq/Build/Products/Debug/BeTimeful.app/
2022-02-08 10:19:49.047076-0500 BeTimeful[2022:19013] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: $RCAnonymousID:aa4a103e51de49bab5fdeda8181d87dc
2022-02-08 10:19:49.048031-0500 BeTimeful[2022:19013] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /receipts
2022-02-08 10:19:49.048112-0500 BeTimeful[2022:19013] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
2022-02-08 10:19:49.245435-0500 BeTimeful[2022:19671] [Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 304
2022-02-08 10:19:49.245865-0500 BeTimeful[2022:19671] [Purchases] - ERROR: 😿‼️ The receipt is not valid.
2022-02-08 10:19:49.246095-0500 BeTimeful[2022:19013] [Purchases] - DEBUG: 💰 Finishing transaction BeTimeful_59.88_1Y_1w0 3 ((null))
2022-02-08 10:19:49.246165-0500 BeTimeful[2022:19671] [Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
2022-02-08 10:19:49.276898-0500 BeTimeful[2022:19427] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: BeTimeful_59.88_1Y_1w0 3 ((null) (null)) (null) - 1
```

**Comment by Daniyaldehleh** [comment]
You guys are champions!! We were literally stuck in this for 2 months! As soon as we took storeKit file out, everything started working. I hope not having a storeKit file in our app wouldn't stop us from getting approved. 

Only questions left:
1. In my sandbox it shows:
![Screen Shot 2022-02-08 at 12 37 39 PM](https://user-images.githubusercontent.com/58639693/153044031-bd83c21e-9e52-4a69-8283-121a72a3bbd0.png)
the sandbox user paid $0 instead of $75. Is this because it's a sandbox user or is something not working well? Cause I do see the sandbox revenue box increasing.

2. Once I took storekit file out, I started seeing this popup hitting buy:
 <img width="304" alt="Screen Shot 2022-02-08 at 12 39 26 PM" src="https://user-images.githubusercontent.com/58639693/153044342-91181395-6169-458b-8d9e-38405126abf5.png">
is this normal to occur? or is this native or something extra that's coming from code/revenueCat?

**Comment by Daniyaldehleh** [comment]
@aboedo No worries at all. You're right after my first successful sandbox, purchase I do start seeing the option.

**Comment by aboedo** [comment]
@Daniyaldehleh I'm glad things are working as expected now! 

>  As soon as we took storeKit file out, everything started working. I hope not having a storeKit file in our app wouldn't stop us from getting approved.

No worries there, you're good. StoreKit Configuration files are a fairly new feature that's exclusively used for testing, and not required for an app to ship. In fact, that configuration file doesn't work in production, since the production configuration is done through App Store Connect.

> Once I took storekit file out, I started seeing this popup hitting buy:

Yeah, that's expected. It's done automatically by macOS, and it's pretty similar to what real users would see when making a purchase in production, it's meant to mimic that. 

I'll let @codykerns answer the question about the price displayed on the dashboard
