### ISSUE TITLE
4.0.0: Missing parity for SKProduct fields

### ISSUE THREAD

**Issue by hansemannn** [RevenueCat/purchases-ios#1277]
**Describe the bug**
It seems like many `SKProduct` fields are still missing in the abtracted `StoreProduct` class:
- `introductoryPrice` (mapped to `introductoryDiscount`):
  - `localizedPrice`
  - `localizedSubscriptionPeriod`
  - `numberOfPeriods`
- `discounts`
  - `numberOfPeriods`
  - `type`
- `priceLocale`  

**Environment**
   1. Platform: iOS
   2. SDK version: 4.0.0 RC.2
   3. OS version: iOS 15.3
   4. Xcode version: 13.2
   5. How widespread is the issue: 100 %

**Workaround**
We can probably use the `sk1Product` everywhere for now, is that correct? But then again, `purchase(...)` does not work anymore, because it does not take an `SKProduct` anymore. I feel like this is not ready for production, yet.

**Comment by aboedo** [comment]
I forgot to address the last bit: 

> We can probably use the sk1Product everywhere for now, is that correct? But then again, purchase(...) does not work anymore, because it does not take an SKProduct anymore

Yes, you can still obtain the sk1Product everywhere (and soon we'll make it possible to use sk2 under the hood and you'll be able to opt into getting the sk2Product instead. 

We provide a few alternatives for `purchase(...`. Some are meant for devs using our [Offerings system](https://docs.revenuecat.com/docs/entitlements) so they take in a `Package`. 

But for devs who'd like to use the products directly, the thinking is that you'd fetch them by using [`getProducts(...)`](https://revenuecat-docs.netlify.app/documentation/revenuecat/purchases/getproducts(_:completion:)), which returns `StoreProduct` objects, and then you'd pass those into `https://revenuecat-docs.netlify.app/documentation/revenuecat/purchases/purchase(product:)`. 

This breaks if you're performing the `SKProductsRequest` yourself, though. Our thinking is that you could just use our methods to get the products, which should be easier in terms of code, and also handles caching. 

Let me know if that makes sense.

**Comment by aboedo** [comment]
@hansemannn did you get a chance to check the fields to see if they're useful? Any thoughts on how we could surface them in a way that's easier to find?

**Comment by hansemannn** [comment]
Hi there! It looks really good already, thank you for the detailed responses! We will give it a shot this week, but looking at your references, we should be fine!

**Comment by aboedo** [comment]
@hansemannn thanks for getting back to us! Let me know if you run into any issues or if you find anything confusing! Have a great week!
