### ISSUE TITLE
Missing step in your doc?

### ISSUE THREAD

**Issue by Daniyaldehleh** [RevenueCat/purchases-ios#1337]
Hi there,
In your [doc](https://docs.revenuecat.com/docs/macos) you haven't mentioned on whether or not to add 

![Screen Shot 2022-02-23 at 1 12 54 PM](https://user-images.githubusercontent.com/58639693/155381276-307dd1af-87d0-453f-929e-886f98ac8a1a.png) to frameworks & libraries of the app target for Purchases or PurcahsesCoreSwift. I'd like to know whether this step is necessary for macOS or IOS? & whether it should be Embed & Sign or Do not Embed?

**Comment by joshdholtz** [comment]
@Daniyaldehleh Hey! Are you looking to install with CocoaPods or through SPM? It looks like CocoaPods from your screenshot but just wanted to to make sure!

If you are using CocoaPods, you won't need to add a framework or library. The CocoaPods project/workspace will take care of that for you.

Hope this helps!
