### ISSUE TITLE
StoreProduct public initializer [4.0.0-rc.4]

### ISSUE THREAD

**Issue by delba** [RevenueCat/purchases-ios#1340]
Hi,

In some cases, we need to initiate a purchase with a `SKProduct` but the new API only takes `StoreProduct` as a parameter and doesn't provide a public initializer for `StoreProduct` ([see L242](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift#L242)).

```swift
class PaywallManager: PaywallDelegate {
    func purchase(product: SKProduct) {
        let product = StoreProduct(sk1Product: product) // <- we can't do that

        Purchases.shared.purchase(product: product) { transaction, purchaserInfo, error, userCanceled in
              // ....
        }
    }
```

Could we have public `StoreProduct` initializers ? Thanks !

**Comment by NachoSoto** [comment]
👍🏻 I don't see a problem making this `public`.

**Comment by delba** [comment]
Awesome, thank you very much !
