### ISSUE TITLE
[Crash] SKProductRequest for removed product (invalid product) but it still present in receipt

### ISSUE THREAD

**Issue by Fl0p** [RevenueCat/purchases-ios#135]
This line will call with empty array:
https://github.com/RevenueCat/purchases-ios/blob/master/Purchases/RCStoreKitRequestFetcher.m#L172

And it will cause crash here
https://github.com/RevenueCat/purchases-ios/blob/3.0.0-beta/Purchases/Public/RCPurchases.m#L955

**Comment by gonchar** [comment]
+1

**Comment by jeiting** [comment]
Yeah, we can't assume the products array isn't empty. This line here has that implicit assumption: 
https://github.com/RevenueCat/purchases-ios/blob/3.0.0-beta/Purchases/Public/RCPurchases.m#L922

We'll whip up a fix.

**Comment by gonchar** [comment]
Hey @jeiting! Really sorry to bother you with these kind of questions, but it will help us to schedule our release better. Do you have any rough estimates for fixing this issue or releasing milestone 3.0? 

Thanks in advance! Our team is very excited to start using RevenueCat!

**Comment by Fl0p** [comment]
❤️ 

hotfix
```
pod 'Purchases', :git => 'git@github.com:RevenueCat/purchases-ios.git', :commit => 'acc6d198c89748d201cc5f6421c7ff4325503585'
```

**Comment by vegaro** [comment]
Thanks for reporting! Just made the release https://github.com/RevenueCat/purchases-ios/releases/tag/3.0.0-beta.2 that should include the fix
