### ISSUE TITLE
Workspace Integrity error after upgrading to purchases-ios 4.0.0

### ISSUE THREAD

**Issue by tijs** [RevenueCat/purchases-ios#1355]
I have just updated my project from Purchases-ios 3 to v4.0.0. While the migration steps seem to work fine and my project still builds I do now get an annoying message in the project navigator:

<img width="313" alt="Schermafbeelding 2022-03-04 om 11 01 11" src="https://user-images.githubusercontent.com/3108/156742972-f7bcdb59-0b8c-4978-84a6-5954ff701be2.png">

```
Workspace Integrity Group
<snip>/SourcePackages/checkouts/purchases-ios/IntegrationTests/PurchaseTester/WatchPurchaseTester Couldn't load project
<snip>/SourcePackages/checkouts/purchases-ios/IntegrationTests/PurchaseTester/PurchaseTester Couldn't load project
<snip>/SourcePackages/checkouts/purchases-ios/IntegrationTests/PurchaseTester/WatchPurchaseTester Extension Couldn't load project
```

Xcode seems to have an issue with some of the legacy example projects in the SPM dependency folder?

1. Environment
   1. Platform: iOS
   2. SDK version: 4.0.0
   3. OS version: Mac OS 12.2.1
   4. Xcode version: 13.2.1

**Comment by taquitos** [comment]
I find the order:

- quit xcode
- delete derived data
- reopen project

to be the most effective 😄
