### ISSUE TITLE
`invalidatePurchaserInfoCache` not migrable by XCode on version 4.0.0

### ISSUE THREAD

**Issue by unxavi** [RevenueCat/purchases-ios#1378]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Migration guide here https://revenuecat-docs.netlify.app/documentation/revenuecat/v4_api_migration_guide says 

> Xcode should automatically provide one-click fixes methods and types that have been renamed. For the most part, the migration should be doable by just building and applying Xcode’s automatic fix-its when they pop up.
> 
> If you see any issues or new APIs that fix-its didn’t cover, we’d appreciate [bug reports](https://github.com/RevenueCat/purchases-ios/issues/new?assignees=&labels=bug&template=bug_report.md&title=)! 

`Purchases.shared.invalidatePurchaserInfoCache() ` doesn't offer the option to migrate the API with XCode. I suppose it's `Purchases.shared.invalidateCustomerInfoCache()` the new API, just wanted to give you the heads up

1. Environment
   1. Platform: iOS
   2. SDK version: 4.0.0
   3. OS version: 12.2.1
   4. Xcode version: 13.2.1
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by NachoSoto** [comment]
Great catch! We missed this one, despite it being in the [migration guide](https://revenuecat-docs.netlify.app/documentation/revenuecat/v4_api_migration_guide).

Fixed: #1379.

**Comment by aboedo** [comment]
Thanks so much for reporting!!
