### ISSUE TITLE
Respond to Storefront updates

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#1382]
When the Storefront is changed while the app is live, we have some stuff in cache that needs to be updated. 

This could lead to some issues, [outlined here](https://github.com/RevenueCat/purchases-ios/pull/1374#discussion_r824724896). 

We should: 

- Listen to Storefront updates ([SK2 method here](https://developer.apple.com/documentation/storekit/storefront/storefronts/asynciterator#), [SK1 method here](https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/3242936-paymentqueuedidchangestorefront#))
- When the storefront is updated, clear caches for offerings + ProductsFetcherSK1 and ProductsFetcherSK2
- Bonus points: eagerly re-fetch products that had beeb previously fetched in productsFetchers + re-fetch offerings
- Add a new method in purchasesDelegate that ports that notification over to the developer. 

The case where the storefront is updated while the app is open is fairly rare, so this won't affect many apps in real life. But long-running apps could be affected, and it isn't _impossible_ to run into this. 

At the very least, if we're eagerly refreshing offerings and products when the storefront is updated, apps will get fresh products when calling `getOfferings` again, which might already be enough for most developers.

**Comment by Juanpe** [comment]
I could do it if it's still unassigned 🙂

**Comment by aboedo** [comment]
That makes total sense to me, and it sounds great!!

**Comment by Juanpe** [comment]
Hi guys 👋🏼! To finish this issue, I'd like to do the last task, create a new `PurchasesDelegate` method, but I have a doubt. When should be the best time to call this method?

1. When the Storefront changes WITHOUT waiting to clear and re-fetch the cache stuff.
2. When the Storefront changes and we clear the cache WITHOUT waiting to re-fetch the cache stuff.
3. When the Storefront changes, we clear the cache and re-fetch the cache stuff again.

To me, option 3 would make more sense; maybe the developer needs to refresh the UI. I would even say that we could add two methods when the Storefront changes and the other when re-fetching the cache stuff, although I don't know if we should add so many methods to the delegate protocol.

WDYT? 🤔

**Comment by NachoSoto** [comment]
I'm not sure if we need to add anything. Users can already use `StoreKit.Storefront.updates` to be notified of updates, and manually refetch products if they need to (which thanks to your updates would be up-to-date). Does that make sense?
