### ISSUE TITLE
Debug logs are polluted with "Key 'CodingKeys(stringValue: "ownershipType", intValue: nil)' not found"

### ISSUE THREAD

**Issue by EliotAndres** [RevenueCat/purchases-ios#1392]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
We just updated to 4.0.0. Since then the RevenueCat debug logs show this line very often:
```
[Purchases] - DEBUG: ℹ️ Key 'CodingKeys(stringValue: "ownershipType", intValue: nil)' not found, codingPath: [], description:
No value associated with key CodingKeys(stringValue: "ownershipType", intValue: nil) ("ownershipType"), converted to ownership_type.
```

1. Environment
   1. Platform: iOS
   2. SDK version: 4.0.0
   3. OS version: 14.4.1
   4. Xcode version:  13.3 beta 3
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
It could be linked to iOS 14 or to the fact that this phone was previously running a previous version of the RevenueCat SDK.

**Comment by vegaro** [comment]
Thanks for opening @EliotAndres . It looks like `ownershipType` is not always present in the response we get from our backend. We can default to `PURCHASED` to silence the log. I will look into it.

**Comment by EliotAndres** [comment]
Thank you for your quick answer. We're about to release the update to production, so let me know if we should wait until this is fixed or if we're good to go. If we're good to go I'll disable debug logs and close this issue

**Comment by vegaro** [comment]
We just merged a PR that removes the log since it wasn't that helpful and it was polluting the debug logs. We'll release it with the next version.

Thanks for opening the issue @EliotAndres
