### ISSUE TITLE
Error when not configuring optional offerings

### ISSUE THREAD

**Issue by triplef** [RevenueCat/purchases-ios#1395]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
We’re trying to set up RC in observer mode (initially), and for this have set up products and entitlements in the dashboard, but **have not set up offerings** as we have no user for them and they are [documented to be optional](https://docs.revenuecat.com/docs/entitlements#offerings). When launching the app we are getting the following error:

```
[Purchases] - ERROR: 😿‼️ There is an issue with your configuration. Check the underlying error for more details.
[Purchases] - ERROR: 🍎‼️ Error fetching offerings - There's a problem with your configuration. There are no products registered in the RevenueCat dashboard for your offerings. To configure products, follow the instructions in https://rev.cat/how-to-configure-offerings. 
More information: https://rev.cat/why-are-offerings-empty
```

This seems to be because the SDK is extracting the product identifiers from the offerings:
https://github.com/RevenueCat/purchases-ios/blob/595f78551903b3f83aa58f30765f6acba3963df2/Purchases/Purchasing/OfferingsManager.swift#L99-L102

It seem like that offerings are not in fact optional. This should be fixed in either the SDK (preferably), or the documentation.

1. Environment
   1. Platform: iOS/macOS
   2. SDK version: 4.1.0
   3. OS version: iOS 15.4, macOS 12.3
   4. Xcode version: 13.3
   5. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
[debug-logs.txt](https://github.com/RevenueCat/purchases-ios/files/8263391/debug-logs.txt)
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Adding an offering fixes the error.

It’s unclear whether this error is critical when only using observer mode, or whether it can be ignored.

**Comment by vegaro** [comment]
Thanks for the feedback @triplef . Offerings are actually optional, specially for cases like yours, where you use our SDK in observer mode.

I will see what we can do to improve that error message. I don't think we should log an error if there are no configured offerings in our SDK.

**Comment by triplef** [comment]
Thanks for the quick feedback @vegaro!

So observer mode should still work fine despite the error?

**Comment by vegaro** [comment]
Yes. You don't need to configure offerings for observer mode 😊

**Comment by vegaro** [comment]
We updated the log message. We hope that's more clear and less scary 😄
