### ISSUE TITLE
Calling .priceLocale on an offering item storeProduct gives error stating not available in iOS 

### ISSUE THREAD

**Issue by ghb101** [RevenueCat/purchases-ios#1398]
- [ X] I have updated Purchases SDK to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [X ] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

I have declared an Offering, and then I am trying to get the Locale of the specific offering subscription item.  Previously in version 3.x.x I used    offering?.annual!.storeProduct.priceLocale.    Now this receives an error in Xcode stating 'priceLocale' is unavailable in iOS: Use localizedPriceString instead.   I need to get the price Locale as I am taking the annual subscription price and dividing by 12 to show the user the monthly equivalent price for the annual subscription.  Is this not supported in an offering product by RevenueCat anymore?

1. Environment
   1. Platform: iOS
   2. SDK version: 4.1.0
   3. OS version: macOS 12.3
   4. Xcode version: 13.3
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
Not applicable
3. Steps to reproduce, with a description of expected vs. actual behavior
Details in the bug description.
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by aboedo** [comment]
Hi @ghb101, thanks for opening. In our v4 SDK, the `priceLocale` property has been removed, due to technical limitations in StoreKit 2.

However, [`StoreProduct`](https://revenuecat-docs.netlify.app/documentation/revenuecat/storeproduct) provides a [`PriceFormatter`](https://revenuecat-docs.netlify.app/documentation/revenuecat/storeproduct/priceformatter) and a [`localizedPriceString`](https://revenuecat-docs.netlify.app/documentation/revenuecat/storeproduct/localizedpricestring), which should cover just about any use case for the `priceLocale`. 

Hope this helps!

**Comment by ghb101** [comment]
Ah, yes.  Thank you.  I didn't realize that a PriceFormatter was provide.  You are correct...I will be able to work with that.

**Comment by NachoSoto** [comment]
>  I need to get the price Locale as I am taking the annual subscription price and dividing by 12 to show the user the monthly equivalent price for the annual subscription. 

For that you can use the new `StoreProduct.pricePerMonth` and like @aboedo said, `StoreProduct.priceFormatter` to format that :)
