### ISSUE TITLE
.presentCodeRedemptionSheet() does not work on iOS 15.4

### ISSUE THREAD

**Issue by RayHughes** [RevenueCat/purchases-ios#1404]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Since iOS 15.4 the offer redemption sheet is not working. The sheet is displayed with an error stating it cannot connect. This issue does not affect previous iOS versions.

1. Environment
   1. Platform: iOS / React Native
   2. SDK version: Tested with 4.1 / 3.x
   3. OS version: 15.4
   4. Xcode version: Dev 13.3, Bitrise 13.2
   5. How widespread is the issue. Percentage of devices affected. All devices running iOS 15.4. 
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) Pending
3. Steps to reproduce, with a description of expected vs. actual behavior., etc.) Call .presentCodeRedemptionSheet() within a revenuecat project on an iOS device.
5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.) Tested with devices running iOS 15.3, and 14.x
![677485A3-4824-42C0-8EE2-A7485D329247](https://user-images.githubusercontent.com/4381883/159400629-0bef6de0-33ed-4805-b669-1acfd8f2b088.png)

**Comment by aboedo** [comment]
Hi @RayHughes, which environment are you using? 
I.e.:
- Is this in Sandbox, TestFlight or Production? 
- Are you using StoreKit Configuration files? 
- Is this on a physical device or simulator?

We've had some reports of this happening in 15.4 in Sandbox, whereas before it would allow you to enter a code (but it would always say that it was expired), and now it does nothing at all. 

iOS 15.4 introduces the ability to test `presentCodeRedemptionSheet` using StoreKit Configuration Files, but I get the feeling that it might have broken the sheet for Sandbox.

**Comment by mosjwarris** [comment]
we are also experiencing this issue in production, it only occurs on the latest version of iOS, its fine if you dont update the device

**Comment by RayHughes** [comment]
> Hi @RayHughes, which environment are you using? I.e.:
> 
> * Is this in Sandbox, TestFlight or Production?
> * Are you using StoreKit Configuration files?
> * Is this on a physical device or simulator?
> 
> We've had some reports of this happening in 15.4 in Sandbox, whereas before it would allow you to enter a code (but it would always say that it was expired), and now it does nothing at all.
> 
> iOS 15.4 introduces the ability to test `presentCodeRedemptionSheet` using StoreKit Configuration Files, but I get the feeling that it might have broken the sheet for Sandbox.

Production

**Comment by RayHughes** [comment]
iOS 15.4.1 was released. I didn't see anything on the release notes. Dev release doesn't drop until tomorrow.

**Comment by aboedo** [comment]
I tried it out on 15.4.1 and the same bug is present. No updates on the radar either ☹️

**Comment by RayHughes** [comment]
This has been resolved in 15.5 Beta 1

**Comment by aboedo** [comment]
Awesome!!! Thanks for the update @RayHughes!!

**Comment by aboedo** [comment]
Confirmed, here's a video on this on 15.5 beta

![video](https://user-images.githubusercontent.com/3922667/162056895-46e54384-30f5-4088-9aea-817149770fd3.mov)

**Comment by aboedo** [comment]
Update: this is working correctly now on iOS 15.4 as well 🎉

![](https://user-images.githubusercontent.com/3922667/163994016-b70e3de8-9401-497d-88de-18c0490d7361.MP4)

I'm closing this issue for now, but if it's still reproducing on your side, let me know and we'll reopen!
