### ISSUE TITLE
Access to SKProduct.introductoryPrice.numberOfPeriods

### ISSUE THREAD

**Issue by ondrejhanak** [RevenueCat/purchases-ios#1418]
Hi, would it be possible to surface `SKProduct.introductoryPrice.numberOfPeriods` and its SK2 counterpart in SDK v4? Seems like good fit may be `Package.storeProduct.introductoryDiscount`, but I don't see it anywhere (searching SDK source code for `numberOfPeriods`).

I need it for subscription introductory pricing `.payAsYouGo`, where user has price reduction for the first 2 months - 2 should be value of the `numberOfPeriods` attribute.

My current workaround is accessing `Package.storeProduct.sk1Product?.introductoryPrice.numberOfPeriods`, which will break once StoreKit 2 support will be turned on as default.

**Comment by ondrejhanak** [comment]
`StoreKit 2` counterpart seems to be `sk2Product.subscription?.introductoryOffer?.periodCount`.


```
/// The number of periods this offer will renew for.
///
/// Always 1 except for `.payAsYouGo`.
public let periodCount: Int
```

**Comment by aboedo** [comment]
@ondrejhanak Thanks so much for reporting!

You're absolutely correct. We missed that property 😬  

We're going to add it soon. I'll keep this ticket open in the meantime.

**Comment by aboedo** [comment]
attaching the [jira ticket](https://revenuecats.atlassian.net/browse/CF-448?atlOrigin=eyJpIjoiNWFjMTkxNWFkYzYxNGY3YTkzZDQwYjg5NjIyYzlmM2QiLCJwIjoiaiJ9) for internal reference.

**Comment by NachoSoto** [comment]
This is in `main` now and will be in a new release soon!
