### ISSUE TITLE
original_transaction_id (OTI)

### ISSUE THREAD

**Issue by 0xacdc** [RevenueCat/purchases-ios#143]
Can you please add to your SDK original property from apple receipt validation `original_transaction_id` ? 

It is really necessary, because having all users marked as anonymous, it seems to be the only persistent value witch can be used as userID

thanks

**Comment by ViktoriiaKh** [comment]
Hello. I have the same request. Currently original_transaction_id can be only retrieved from PurchaseResultData. Or is there another way?

**Comment by NachoSoto** [comment]
If you need this for non subscriptions, the SDK has `CustomerInfo.nonSubscriptions.transactionIdentifier`.
