### ISSUE TITLE
Cannot upload Carthage build to App Store because it includes x86_64, i386

### ISSUE THREAD

**Issue by roostr** [RevenueCat/purchases-ios#144]
Hi,

I'm trying to upload a beta build of my app, which I just integrated with RevenueCat, to App Store Connect. I'm using Carthage to build the 3.0.0 version of RevenueCat.

I get this error on submission:

```
App Store Connect Operation Error
Unsupported Architectures. The executable for MyApp.app/Frameworks/Purchases.framework contains unsupported architectures '[x86_64, i386]'.

App Store Connect Operation Error
Invalid Segment Alignment. The app binary at 'MyApp.app/Frameworks/Purchases.framework/Purchases' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

App Store Connect Operation Error
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.
```

I'm using Xcode 11.2.1, and I believe my command-line build environment is set up properly:

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

I noticed that you recommend using the `--no-use-binaries` flag in Carthage, and I've tried both with and without that flag. I get the error either way.

```
carthage build --platform ios --configuration Release --no-use-binaries
carthage build --platform ios --configuration Release
```

I'm wondering whether the second and third error might be because of the first one. Do you know what I can do to prevent RevenueCat from building x86 targets when making iOS-only builds using Carthage?

**Comment by vegaro** [comment]
Hi @roostr, when using Carthage to add any framework you have to add a build phase to strip the frameworks. On your application target "Build Phases" settings tab, add a "New Run Script Phase" by pressing the + button with the content `/usr/local/bin/carthage copy-frameworks`. You also need to add the paths to the frameworks you want to use under "Input Files":

```
$(SRCROOT)/Carthage/Build/iOS/Purchases.framework
$(SRCROOT)/Carthage/Build/iOS/Purchases.framework
```

This script is a workaround for an App Store [bug](http://www.openradar.me/radar?id=6409498411401216) where apps with frameworks that contain binary images for the iOS simulator are automatically rejected. 

This tutorial is very good https://www.raywenderlich.com/416-carthage-tutorial-getting-started and has more information around this.

Cheers!

**Comment by roostr** [comment]
Thanks @vegaro!

I did forget this step. I had later fixed it, but I *forgot* to remove it from my "Embed Frameworks" step. So it looks like I was embedding it twice, and one of those was the unstripped binary.

All's well now, thank you! 🙌
