### ISSUE TITLE
🍎‼️ There was a problem with the App Store  SKErrorDomain Error 0 

### ISSUE THREAD

**Issue by gbesler** [RevenueCat/purchases-ios#1495]
Hello everyone,

We are facing a weird error in production which we cannot resolve. 1 of 8 users clicked free trial button in our app gets:

🍎‼️ **There was a problem with the App Store** with mostly "SKErrorDomain Error 0"

I know this is caused by Apple but isn't the ratio 1/8 is too high to get this specific error? This is not happening when user cancels the purchase and we don't know what it is.

The error is our nightmare now and we cannot fix it. Any help is appreciated.

**Comment by joshdholtz** [comment]
Hey @gbesler!

I believe this issue is usually caused by same sort of network error but 1 out of 8 does seem a little high 🤔 It sounds like this could potentially be an issue on Apple's side but we have not seen any reports of this yet.

I've also heard instances where this error was caused by an App Store Connect account not being renewed but that would probably be a 100% failure for all users so that's probably not the issue 🙃 

I have a few questions for you so we can try to narrow this down and get the right conditions on our side to try and reproduce:
1) What version of the SDK are you using?
2) What OS platform and version is this issue happening on? iOS, macOS, or both? (If you know)
3) What kind of production/subscription and free trial are you using?
4) Do you know if these failures are happening in a specific country / region of the world?

Thanks!

**Comment by gbesler** [comment]
Thanks for quick reply. 

Sometimes the ratio is even higher, like 1/7 or 1/6. And this is unique user count not the total number. I mean some users try so hard and get the same error 5-6 times but we don't include total count it in the ratio mentioned.

Do you mean Developer Membership expiration date by App Store Account renewal? If so we have a valid developer membership date. It is not expired.

1- The latest one with CocoaPods
2- iOS only we don't have macOS support
3- Happening after click Free Trial event. We don't know how to reproduce.
4- Happens all around the world. US, UK, Germany, Italy etc. Also on Wifi or LTE.

Seriously weird.

**Comment by joshdholtz** [comment]
@gbesler Thanks for the quick answers!

>Do you mean Developer Membership expiration date by App Store Account renewal? If so we have a valid developer membership date. It is not expired.

Yup, that is what I meant! Sorry about confusion 😛 I assumed you did but had to ask 🤷‍♂️ 

>1- The latest one with CocoaPods

You are on the latest v3 or v4? v3 is `Purchases` in cocoapods but v4 got migrated over to `RevenueCat` name. Just want to verify I'm trying to reproduce on the correct one 😊

**Comment by gbesler** [comment]
Yes, we use `RevenueCat`. Just integrated last week.

**Comment by joshdholtz** [comment]
@gbesler Thank you! I'm going to see if I can reproduce but I'll also keep on the lookout for others reporting similar things too.

Oh, one other question I meant to ask but forgot was... when did you see this start happening (or start happening with the elevate error rate)?

**Comment by gbesler** [comment]
Well, it has been like that since we discovered it, 3-4 months ago. Probably it was like that before we discovered too.

**Comment by joshdholtz** [comment]
@gbesler Hey! I talked some of the team to see if anybody else had any idea why you'd be seeing an elevated level of `SKErrorDomain Error 0`. 

One of the thoughts would be an undocumented error is happening and this `SKErrorDomain Error 0` is what is getting presented. This error _should_ come with some more detailed information. I believe the `SKErrorDomain Error 0` is just the localized description.

I don't think there is much we can do unless we are able to see more information. Having the following would be helpful:
- More debug logs (see https://docs.revenuecat.com/docs/debugging)
- iOS versions this is happening on

This also might be a reason to open a TSI with Apple if this was also happening before using RevenueCat - https://developer.apple.com/support/technical/

**Comment by NachoSoto** [comment]
We just released [v4.3.0](https://github.com/RevenueCat/purchases-ios/releases/tag/4.3.0). We'd appreciate if you can give that a try since it has many improvements to error reporting.

**Comment by gbesler** [comment]
is v4.3.0 on CocoaPods? I use it with pods and can't use v4.3.0 with pods.
