### ISSUE TITLE
'Purchases' is not a member type of 'Purchases'

### ISSUE THREAD

**Issue by jln19** [RevenueCat/purchases-ios#153]
Hi, super excited to have found this potential IAP solution! But straightaway I'm getting an error:

```
Purchases.shared.offerings { (offerings, error) in
            if let packages = offerings?.current?.availablePackages {
                // Display packages for sale
            }
        }
```

The error:
```Printing description of offerings:
expression produced error: error: /var/folders/9m/qr_cnwq903n_f_xf0nbgcf140000gn/T/expr9-ab7010..swift:1:90: error: 'Purchases' is not a member type of 'Purchases'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Swift.Optional<Purchases.Purchases.Offerings>>(bitPattern: 0x10be7d6e0)!.pointee)
```

Edit: Seems I get this error upon any attempt at using the API:

```
Purchases.shared.purchaserInfo { (purchaserInfo, error) in
            // access latest purchaserInfo
        }
```

**Comment by jln19** [comment]
Hmm. Running this a day later with no changes and the error has gone away...

**Comment by jln19** [comment]
I also tried creating a brand new project in Xcode and only adding the following code in didFinishLaunching (after installing the Pod). I still get the same error on a breakpoint on if let packages = ...

```
        Purchases.debugLogsEnabled = true
        Purchases.configure(withAPIKey: "my-api-key")
        
        Purchases.shared.offerings { (offerings, error) in
            if let packages = offerings?.current?.availablePackages {

            }
        }
```

**Comment by jeiting** [comment]
What version of Purchases is actually installed? Your cocoapods might be out of data and these examples reference a more recent version of Purchases.

**Comment by jln19** [comment]
@jeiting `pod 'Purchases', '3.0.0'`

**Comment by jeiting** [comment]
Is it possible your Xcode intermediates are in a bad state?

Have you tried deleting DerivedData?

**Comment by jln19** [comment]
So after deleting DerivedData, this no longer shows an error:

```
Purchases.shared.purchaserInfo { (purchaserInfo, error) in
            // I get Optional<RCPurchaserInfo> here
        }
```

However, when I try this: 

```
Purchases.shared.offerings { (offerings, error) in
        }
```

If I do `po offerings` I get 

```
▿ Optional<RCOfferings>
  - some : <Offerings {
	currentOffering=(null)>
```

If I hover over `offerings` in Xcode I get the error:

```
Printing description of offerings:
expression produced error: error: /var/folders/9m/qr_cnwq903n_f_xf0nbgcf140000gn/T/expr45-d72fda..swift:1:90: error: 'Purchases' is not a member type of 'Purchases'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Swift.Optional<Purchases.Purchases.Offerings>>(bitPattern: 0x10a329ea0)!.pointee)
```

**Comment by jln19** [comment]
I think the "expression produced error" thing may be a Swift/Xcode issue. I think the real problem is that I'm not getting any offerings. I have them set up in the admin as well as marking one of them as "current". DEBUG shows that I have invalid product identifiers. I've triple-checked those though and I can successfully pull products down from native IAP code and SwiftyStoreKit. I submitted a tech support ticket about this over the weekend if you have a minute to check that out. 🙏

**Comment by vegaro** [comment]
Closing this since it looks like it's been solved and another issue has been opened.

**Comment by shibin919** [comment]
Unfortunately, I'm hitting the same thing...
