### ISSUE TITLE
Crash when retrieving purchaser information from cache

### ISSUE THREAD

**Issue by jkichline** [RevenueCat/purchases-ios#156]
I have a crash occurring here since appUserID is nil for some reason...

RCDeviceCache.m (Line 88)
- (NSString *)purchaserInfoUserDefaultCacheKeyForAppUserID:(NSString *)appUserID {
    return [RCPurchaserInfoAppUserDefaultsKeyBase stringByAppendingString:appUserID];
}

Should at least protect from nullable input like this.

- (NSString *)purchaserInfoUserDefaultCacheKeyForAppUserID:(NSString *)appUserID {
	if(appUserID == nil) { return nil; }
    return [RCPurchaserInfoAppUserDefaultsKeyBase stringByAppendingString:appUserID];
}

Or is there a reason why appUserID would be nil?

**Comment by aboedo** [comment]
@jkichline might this be related to https://github.com/RevenueCat/purchases-ios/issues/141? It might be another manifestation of the same issue - the SDK currently relies on `NSUserDefaults`, so if it's flushed, we might be missing the `appUserID`. 
If it is indeed related, then as I mentioned on the other issue, we're looking to move away from `NSUserDefaults`. In the meantime, one way to work around this would be to make sure to only remove they keys that your app users from `NSUserDefaults`, so that keys coming from RevenueCat don't get deleted.

**Comment by aboedo** [comment]
@jkichline update on this: The SDK allows for you to specify a separate instance of `NSUserDefaults` to be used.
By specifying a different instance, you can safely delete your app's standard UserDefaults without running into this issue. 
Note that if you want to delete the info stored on the RevenueCat SDK, you have to call `resetWithCompletionBlock`. 

Here's an example of sending in a different user defaults instance for the RevenueCat SDK: 
```swift
guard let revenueCatUserDefaults = UserDefaults.init(suiteName: "com.myapp.revenuecat") else {
    fatalError("can't create user defaults for RevenueCat domain")
}
Purchases.configure(withAPIKey: "your api key here",
                    appUserID: nil,
                    observerMode: false,
                    userDefaults: revenueCatUserDefaults)
        
```

**Comment by jkichline** [comment]
How does this effect currently active apps and is there a way to transition to the new user defaults? Also, do you have a prefix you use for RevenueCat specific keys? I can implement that into my "reset settings" tool to avoid wiping out RevenueCat...

**Comment by aboedo** [comment]
All of the keys used by the SDK are prefixed with `com.revenuecat.userdefaults`, for example `com.revenuecat.userdefaults.appUserID`.
If you avoid deleting those, that’ll probably be the easiest and safest path for an existing app.
Setting a different domain should be safe, but note that the purchases instance won’t see any stored data from the standard domain and will assume that the user hasn’t logged in unless you pass in the appUserID value.
It's the equivalent of the behavior you get when calling `resetWithCompletion`

**Comment by aboedo** [comment]
closing for now since there's a workaround, but feel free to reopen if you run into any more issues with this

**Comment by om-ha** [comment]
While the solution you guys are showing here works, it's not included in Flutter pub :(

https://github.com/RevenueCat/purchases-flutter/blob/e1b896d4d41849bef31817d0b1abf2dc47942277/lib/purchases_flutter.dart#L34

Guess I'll have to write a platform channel method just to setup RevenueCat's Purchases

**Comment by aboedo** [comment]
@om-ha our Flutter SDK uses the `purchases-ios` library under the hood, so we first develop the changes on `purchases-ios`, release them, and then we update the Flutter SDK (as well as ReactNative, Unity and Cordova). 
So the changes will land on the Flutter version pretty soon, but they get merged into this codebase first. Sorry for the delay.

**Comment by om-ha** [comment]
No problem @aboedo , I do realize this limitation and that changes are propagated in a delayed manner to Flutter version.

Something way simpler than this issue, and while you're at it, there's this other change that takes zero time but already exists on iOS. Just needs definition for flutter: [issue on flutter ](https://github.com/RevenueCat/purchases-flutter/issues/34) and its original solved [issue on ios](https://github.com/RevenueCat/purchases-ios/pull/191)
