### ISSUE TITLE
swiftUI example

### ISSUE THREAD

**Issue by mkalayci35** [RevenueCat/purchases-ios#157]
please add swiftUI example

**Comment by vegaro** [comment]
Adding a full SwiftUI example is not part of our roadmap at the moment. Is there any particular question you have regarding the integration of our SDK?

Thanks!

**Comment by ozgurshn** [comment]
I wrote a wrapper for SwiftPaywall to use it in SwiftUI. 
https://gist.github.com/ozgurshn/73d8d583fbc8916bae2abd7ad61b87ef

**Comment by aboedo** [comment]
hey @ozgurshn thanks for posting!! It'll be super helpful to folks moving to SwiftUI 💪

**Comment by ozgurshn** [comment]
Nice ho hear that @aboedo 💪
