### ISSUE TITLE
`showManageSubscriptions()` never uses native AppStore method

### ISSUE THREAD

**Issue by philmitchell** [RevenueCat/purchases-ios#1594]
- [ x] I have updated Purchases SDK to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [ x] I have searched the [Community](https://community.revenuecat.com)
- [x ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

Even on a device running iOS15, `Purchases.showManageSubscriptions()` loads the subscriptions UI via Safari rather than a native action sheet. 

1. Environment
   1. Platform: iOS
   2. SDK version: 4.3
   3. StoreKit 2 enabled (Y/N): Have tried it both ways
   4. OS version: 15.4.1
   5. Xcode version: 13.3
   6. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
Where supported, it should open the native action sheet, which provides a superior UX.

5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

This seems to be because we have:

  `SystemInfo.appleSubscriptionsURL = URL(string: "https://rev.cat/manage-apple-subscription")`

This url never passes the `isAppleSubscription()` test, therefore we always fallback to the `openURL()` method.

**Additional context**

**Comment by aboedo** [comment]
Hi @philmitchell 👋 
Great catch!! That's a refactor gone bad. We'll get it fixed 💪 
Thanks for reporting!

**Comment by NachoSoto** [comment]
Submitted a fix for this. We'll probably have it out in a release later today :)

**Comment by NachoSoto** [comment]
The fix for this is out in 4.4.0
