### ISSUE TITLE
checkTrialOrIntroductoryPriceEligibility won't call completion on simulator

### ISSUE THREAD

**Issue by fluidvm** [RevenueCat/purchases-ios#1627]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

1. Environment
   1. Platform: iOS
   2. SDK version: 3.13.1
   3. StoreKit 2 enabled (Y/N): N
   4. OS version: 15.4
   5. Xcode version: 13.3
   6. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Similar to https://github.com/RevenueCat/purchases-ios/issues/341

**Comment by beylmk** [comment]
Hi @fluidvm, unfortunately I'm unable to reproduce this...can you please share how and where you're calling this? And do you get a prompt to log in to the app store?
