### ISSUE TITLE
[Xcode 14] Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by davidrothera** [RevenueCat/purchases-ios#1660]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Refuses to build with Xcode 14b1 due to requirement for stored properties to not have availability markings

1. Environment
   1. Platform: Xcode 14 (new beta)
   2. SDK version: 4.5.1
   3. StoreKit 2 enabled (Y/N): n/a
   4. OS version: n/a
   5. Xcode version: Xcode 14 beta 1
   6. How widespread is the issue. Percentage of devices affected: 100% unable to build
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by NachoSoto** [comment]
Thanks for the report!
I'm working on this right now.

**Comment by davidrothera** [comment]
https://github.com/RevenueCat/purchases-ios/blob/main/Sources/Purchasing/ProductsManager.swift#L27 is an example of one of the callsites broken

**Comment by davidrothera** [comment]
> Thanks for the report! I'm working on this right now.

Awesome thanks for the quick work, trying to work out what/if things are broken in iOS 16 <3
