### ISSUE TITLE
Xcode 14 Support - "Stored properties cannot be marked potentially unavailable with '@available'"

### ISSUE THREAD

**Issue by gdavis** [RevenueCat/purchases-ios#1667]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Xcode 14 beta was released yesterday, and the latest version 4.5.1 currently does not compile when linked using the Swift Package Manager. When compiling, Xcode will encounter the following issue:

```
BeginRefundRequestHelper.swift:27:6: error build: Stored properties cannot be marked potentially unavailable with '@available'
```
```
ProductsManager.swift:27:6: error build: Stored properties cannot be marked potentially unavailable with '@available'
```

Interestingly enough, if I checkout my own fork of the repo, and link it as a local package, the app compiles successfully. This may be an Xcode 14 beta issue.

1. Environment
   1. Platform: macOS 12.4 with Xcode 14 beta
   2. SDK version: 4.5.1
   3. StoreKit 2 enabled (Y/N): N
   4. OS version: iOS 14+, macOS 11+
   5. Xcode version: Xcode 14 beta
   6. How widespread is the issue. Percentage of devices affected. – 100%
2. Debug logs: see issues above
3. Steps to reproduce, with a description of expected vs. actual behavior
   1. Checkout RevenueCat 4.5.1 as a swift package
   2. Compile application
   3. Observe errors listed above regarding stored properties cannot be marked unavailable.

**Additional context**
This is likely low priority since Xcode beta was just released. With the nice improvements to Xcode, I was just hoping to get dirty with the new version ASAP. 

Since I am able to link to a local package on my file system without the same error, this is likely an Xcode issue. However I thought it might be good to have an issue open for other users wanting to get on the latest Xcode build, and to track the fix that may come from either RevenueCat or Apple.

Here's a screenshot showing my local fork of the repo that works (showing that it is NOT within the standard Package Manager list):
![image](https://user-images.githubusercontent.com/110691/172483264-2ffa3df9-f769-4a47-83b7-cd3a800456f7.png)

When normally linked using the Project's `Swift Packages` settings, the package fails to build.

**Comment by taquitos** [comment]
Fixed in: https://github.com/RevenueCat/purchases-ios/pull/1661
We'll be doing a release soon 😄

**Comment by gdavis** [comment]
Awesome! Thanks so much for the lightning fast reply @taquitos

**Comment by taquitos** [comment]
Thank you for taking the time to make reports!

**Comment by gdavis** [comment]
Thank you @NachoSoto !
