### ISSUE TITLE
Configuration.Builder .with(appUserID: )  not accepting nil as a parameter

### ISSUE THREAD

**Issue by unxavi** [RevenueCat/purchases-ios#1717]
- [x ] I have updated Purchases SDK to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [ x] I have searched the [Community](https://community.revenuecat.com)
- [ x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
This might be a bug on the SDK or on the documentation. The documentation of the SDK stays:

```
 /**
         * Set an `appUserID`.
         * - Parameter appUserID: The unique app user id for this user. This user id will allow users to share their
         * purchases and subscriptions across devices. Pass `nil` or an empty string if you want ``Purchases``
         * to generate this for you.
         *
         * - Note: Best practice is to use a salted hash of your unique app user ids.
         *
         * - Important: Set this property if you have your own user identifiers that you manage.
         */
        @objc public func with(appUserID: String) -> RevenueCat.Configuration.Builder
```

But the param for `appUserID`is `String` and not `String?`

1. Environment
   1. Platform: iOS
   2. SDK version: 3.7.0
   3. StoreKit 2 enabled (Y/N): N
   4. OS version: All
   5. Xcode version: 13.4.1
   6. How widespread is the issue. Percentage of devices affected.

**Additional context**
None

**Comment by aboedo** [comment]
Hey @unxavi! Thanks for opening!! 

Perhaps we could do a better job at documenting the intended usage here. 

From our [SDK reference docs](https://revenuecat.github.io/purchases-ios-docs/4.6.1/documentation/revenuecat/purchases/configure(with:)): 

```swift
 Purchases.configure(
     with: Configuration.Builder(withAPIKey: Constants.apiKey)
              .with(usesStoreKit2IfAvailable: true)
              .with(observerMode: false)
              .with(appUserID: "<app_user_id>")
              .build()
     )
```

So... basically you don't need to call `.with` unless you want to specify the `appUserID`. If you don't call it at all, it's the same as passing `nil`. 

I.e.: in order to pass in `nil`, just call
```swift
 Purchases.configure(with: "<api_key>")
```

I hope that makes sense!

**Comment by unxavi** [comment]
Yes, that makes sense... what i meant is that the docs says that you can pass nil, and maybe we should fix the docs.

Can I trust the part that says `or an empty string if you want ``Purchases``  * to generate this for you.` ?

**Comment by aboedo** [comment]
@unxavi that's a great point, we're updating the docs to make sure they all include the latest syntax. 
Passing in an empty string is the same as passing in `nil` in the old syntax, or not passing in anything at all in the new syntax - it'll make the SDK auto-generate an appUserID

**Comment by jhoanarango** [comment]
Hello @aboedo, 

While doing the change on the 

```swift

Purchases.configure(with: Configuration.Builder(withAPIKey: "<api_key>"))

```

I am getting an error that says:  *Cannot convert value of type 'Configuration.Builder' to expected argument type 'Configuration'*

I am using the latest release, which I just updated a few minutes ago.

**Comment by aboedo** [comment]
My apologies, I forgot to add `.build()` at the end. 
The example should have been: 
```swift
Purchases.configure(with: Configuration.Builder(withAPIKey: "<api_key>").build())
```

**Comment by jhoanarango** [comment]
Disregard my last comment, I noticed that I was missing the .build(). 

I was guided by the "Basic Configuration" documentation on the website. [Here](https://docs.revenuecat.com/docs/configuring-sdk) which is missing the .build()

**Comment by aboedo** [comment]
I updated the example in the docs as well, thanks for reporting!

**Comment by aboedo** [comment]
@unxavi @jhoanarango I'm closing this issue for now, but let us know if you're still running into any issues. 

Also, inspired by the discussion here, we are preparing an update that adds an overload to `.configure` that takes a builder and automatically calls `.build()` on it. This will likely prevent future devs from running into this confusion again 😃

Keep the feedback coming!
