### ISSUE TITLE
Purchases.shared.checkTrialOrIntroDiscountEligibility - always returning "unknown"

### ISSUE THREAD

**Issue by JMCPH** [RevenueCat/purchases-ios#1746]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
We having issues with fetching the trial or intro discount eligibility after updating to the latest RevenueCat version.
The method we are using is the `Purchases.shared.checkTrialOrIntroDiscountEligibility`, but it always returns `unknown`.

We have tested this on the simulator, physical devices, new sandbox users, clearing sandbox users purchase history etc., but nothing seems to work. Even if a user is ineligible, it still returns `unknown`

1. Environment
   1. Platform: iOS
   2. SDK version: 4.6.1
   3. StoreKit 2 enabled (Y/N): Y
   4. OS version: 15.3.1
   5. Xcode version: 13.4.1
   6. How widespread is the issue. Percentage of devices affected: 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by NachoSoto** [comment]
The logic for this is very different in SK1 and SK2. Can you confirm you're indeed passing `useStoreKit2IfAvailable: true` to `configure`?

**Comment by JMCPH** [comment]
@aboedo we are upgrading from 4.1 to the current version. 
We have found out that it works in development builds from Xcode to device, as long as we have a Configuration StoreKit file and StoreKitTestCertifikate. That being said, we are still getting .unknown in TestFlight builds.

@NachoSoto We have just uploaded a new version in TestFlight where this have been set when configuring the Purchases instance. I will keep you posted if this solves the issue.

Thank you both for your time

**Comment by aboedo** [comment]
@JMCPH I think this might indicate an issue with your setup in App Store Connect: 
The fact that the eligibility is loading correctly with a configuration file, but not without it, suggests that you may have products set up in your configuration file that aren't set up in App Store Connect or the RevenueCat dashboard. 

Maybe there's a small typo or a difference in the naming of the products, so they don't match?

**Comment by JMCPH** [comment]
@aboedo @NachoSoto Thank you for your time and help.
We have resolved the issue by passing the `useStoreKit2IfAvailable: true` when configuration the instance.

The reason for not adding it right away, was that it's marked as `beta` in the [documentation](https://docs.revenuecat.com/docs/configuring-sdk#additional-configuration-options). I think it would be a great idea to add some documentation about the `checkTrialOrIntroDiscountEligibility` function in this [section](https://docs.revenuecat.com/docs/displaying-products) as well.

Again, thank you for your help!
