### ISSUE TITLE
Bug: CheckTrialOrIntroDiscountEligibility too slow

### ISSUE THREAD

**Issue by jesus-mg-ios** [RevenueCat/purchases-ios#1893]
- [X] I have updated Purchases SDK to the latest version
- [-] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [X ] I have searched the [Community](https://community.revenuecat.com)
- [ X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

We are using checkTrialOrIntroDiscountEligibility in iOS with swift  after get the product, and we notice that this call is too slow (even 45s - 1 min). 
```
Purchases.shared.checkTrialOrIntroDiscountEligibility(productIdentifiers: ["productIdentifier"]) { result in
....
}
```

1. Environment
   1. Platform: iOS
   2. SDK version: 4.10
   3. StoreKit 2 (_enabled with `useStoreKit2IfEnabled`_) (Y/N): N
   4. OS version: 15.5
   5. Xcode version: 13.4.1
   6. How widespread is the issue. Percentage of devices affected: Unknown/Random
**Additional context**

Environment: Real device & simulator. iOS 15.5
SDK Version: "4.10.0"
Code that is too slow
```
Purchases.shared.checkTrialOrIntroDiscountEligibility(productIdentifiers: ["productIdentifier"]) { result in
....
}
```

**Comment by aboedo** [comment]
@jesus-mg-ios would you mind trying out the branch from this PR to see if you get better results? https://github.com/RevenueCat/purchases-ios/pull/1894

It just disables SK2 for this particular operation.

**Comment by jesus-mg-ios** [comment]
Thanks, I'm gonna try it!

**Comment by jesus-mg-ios** [comment]
Hi @aboedo, the change was amazingly faster.

We're gonna share with you the logs before and 
after the change.

[RevenueCatLogsBeforeFixBranch_4_11_0 copy.txt](https://github.com/RevenueCat/purchases-ios/files/9610523/RevenueCatLogsBeforeFixBranch_4_11_0.copy.txt)

[RevenueCatLogsAfterFixBranch_4_12_0 copy.txt](https://github.com/RevenueCat/purchases-ios/files/9610508/RevenueCatLogsAfterFixBranch_4_12_0.copy.txt)

**Comment by aboedo** [comment]
@jesus-mg-ios thanks for getting back to us. 

This confirms that the issue is StoreKit 2's underlying API being very slow for this... 

Which is frankly unfortunate because it's the only one that's technically guaranteed to be perfectly accurate (with StoreKit 1, 100% accuracy for intro eligibility is technically not possible 🤕). It will still be correct for the vast majority of use cases, though. 

We're going to think about the best way to provide flexibility for this API. 

cc @NachoSoto

**Comment by jesus-mg-ios** [comment]
@aboedo we're experimenting delays also in the simulator (with no appleid configured and not Apple ID signed up).
Is it expected?

cc: @unxavi

**Comment by timfraedrich** [comment]
We are also experiencing this issue, might it be possible to request and cache the eligibility properties together with the offerings on app start? From my understanding the values should not change except if a product is purchased at which point RevenueCat should know about it and could invalidate the cache. I may be missing something here though.

**Comment by tcwalther** [comment]
@timfraedrich I just came here because of the same issue - being able to cache offerings and eligibility would be great. Afaics this would require making `RevenueCat.Package` conform to `Codable`.

**Comment by jesus-mg-ios** [comment]
And is possible to use a configuration parameter to disable (who wants), the case that @aboedo revert? I think that solve our problem for the moment.

**Comment by tcwalther** [comment]
@NachoSoto afaics one can encode at least an SK2Product using `jsonRepresentation`, but I can't see how to decode it again.

I think in general though, being able to cache as much as possible of the pricing would be highly desirable. In our app, for example, we just added a lock screen widget that on the free version just sends a user to a paywall. That could very well happen from a cold start, and it would be great if we could display prices instantly.

**Comment by aboedo** [comment]
Hey folks, thanks for the feedback! 
We're discussing best approaches here. Caching is possible, although like all caching things it's not trivial and we'd want to get it right. So we'll add it, but I don't have an ETA for that yet and it might take us a bit longer to get to it.  

In the meantime, we're also discussing the possibility of reusing the `useSK2IfAvailable` flag that's available when configuring the SDK to control the implementation of this method too. That would provide a low-risk solution that's easy to add on our side. We'll keep you posted!

**Comment by aboedo** [comment]
Update here: we've updated `checkTrialOrIntroDiscountEligibility` so that it uses our StoreKit 1 implementation if `useSK2IfEnabled` = false. 
This will go out very soon in release 4.13.3, PR is here https://github.com/RevenueCat/purchases-ios/pull/1988

**Comment by NachoSoto** [comment]
I also filed [CSDK-493] to add a caching mechanism to `TrialOrIntroPriceEligibilityChecker`.

**Comment by aboedo** [comment]
Final update here: the implementation of `checkTrialOrIntroDiscountEligibility` will now respect the preference for `useStoreKit2IfAvailable`. 
Our latest release uses StoreKit 1 by default, which is the speedy implementation. So this should no longer be a problem by default, and if you're setting `useStoreKit2IfAvailable` to true, changing the value to `false` should solve it.
