### ISSUE TITLE
warning: nil passed to a callee that requires a non-null parameter

### ISSUE THREAD

**Issue by Timac** [RevenueCat/purchases-ios#215]
**Steps to reproduce:**
- Open the Purchases.xcodeproj project in Xcode 11.4
- Choose an iOS Simulator as target
- Perform a static analysis with Product > Analyze

**Result:**
You see 3 warnings "nil passed to a callee that requires a non-null parameter":

1. purchases-ios/Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m:81:5: warning: nil passed to a callee that requires a non-null 2nd parameter
    [self storeAttributeLocallyIfNeededWithKey:key value:value appUserID:appUserID];

2. purchases-ios/Purchases/Public/RCPurchases.m:177:26: warning: nil passed to a callee that requires a non-null 2nd parameter
    RCBackend *backend = [[RCBackend alloc] initWithAPIKey:APIKey platformFlavor:platformFlavor];

3. purchases-ios/Purchases/Public/RCPurchases.m:874:9: warning: nil passed to a callee that requires a non-null 1st parameter
        [self markAttributesAsSyncedIfNeeded:subscriberAttributes appUserID:self.appUserID error:error];

It appears that the methods where nil is passed as parameter can perfectly handled the nil parameter. So I would assume that the keyword nullable is missing from the method prototype.

**Comment by Timac** [comment]
A pull request has been submitted: https://github.com/RevenueCat/purchases-ios/pull/216

**Comment by aboedo** [comment]
Hi! Thanks for reporting and opening the PR! I self-assigned to keep track of it. And I reviewed the PR, one small change and it's good to go.

**Comment by aboedo** [comment]
Release 3.2.2 is out, with the fix included. Check it out! 
And thanks again for bringing this to our attention, and going above and beyond by opening a PR with the fix!! 
Closing this as solved
