### ISSUE TITLE
Can't compile. Package doesn't compile for iOS 13

### ISSUE THREAD

**Issue by bubudrc** [RevenueCat/purchases-ios#2209]
- [X ] I have updated Purchases SDK to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [X ] I have searched the [Community](https://community.revenuecat.com)
- [X ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
I'm getting a bunch of errors on my project, about RevenueCat, after added it.

![Screen Shot 2023-01-12 at 10 35 14 (2)](https://user-images.githubusercontent.com/619159/212082222-9342ed33-6c6f-4308-836d-2803fe09181e.png)

1. Environment
   1. Platform: iOS
   2. SDK version: 4.16.0
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N): N
   4. OS version: 11.6
   5. Xcode version: 13.1 (13A1030d)
   6. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.): I'm have firebase added for analytics and crashlytics

My Configuration:
```
/* Enable debug logs before calling `configure`. */
        if Environment.isDevTarget {
            Purchases.logLevel = .debug
        }

        Purchases.configure(
            with: Configuration.Builder(withAPIKey: Constants.revenueCatApiKey)
                .with(usesStoreKit2IfAvailable: false)
                .build()
        )

        /// - Set the delegate to this instance of AppDelegate. Scroll down to see this implementation.
        Purchases.shared.delegate = self
```

**Comment by NachoSoto** [comment]
The minimum [Xcode version required is 13.2](https://github.com/RevenueCat/purchases-ios#requirements).
Can you update to that version and let us know if you still have any issues?

**Comment by bubudrc** [comment]
Nice. I can confirm. Everithing works good on after install Xcode 13.2

**Comment by NachoSoto** [comment]
Great thanks! Let us know if you need help with anything else.
