### ISSUE TITLE
New Features Trello Link Broken

### ISSUE THREAD

**Issue by rjstelling** [RevenueCat/purchases-ios#230]
The link to the "New Features" Trello board is broken.

Link:
https://trello.com/b/RZRnWRbI/revenuecat-product-roadmap

I'm assuming this has either been removed or made private. Either way it should probably be removed from the docs.

**Comment by vegaro** [comment]
We weren’t doing a good job of keeping it up to date and have decided to sunset it for now. I will remove it from the docs. Thanks for opening this issue
