### ISSUE TITLE
Crash compiling for test

### ISSUE THREAD

**Issue by jesus-mg-ios** [RevenueCat/purchases-ios#2403]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
When I try to compile for test the compiler doesn't end

1. Environment
   1. Platform: iOS
   2. SDK version: 4.17.9
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N): Default
   4. OS version: 16.4
   5. Xcode version: 14.3
   6. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
```
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Running pass 'Function Pass Manager' on module '/Users/USER/Library/Developer/Xcode/DerivedData/Example-cvrnegsiyrpqbbakeqbdlsnbxaws/Build/Intermediates.noindex/RevenueCat.build/UnitTests-iphonesimulator/RevenueCat.build/Objects-normal/x86_64/ASIdManagerProxy.o'.
1.	Running pass 'X86 Assembly Printer' on function '@"$s10RevenueCat9PurchasesC11logOutAsyncAA12CustomerInfoCyYaKFTY0_"'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001060d3300 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001060d22e4 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001060d3910 SignalHandler(int) + 344
3  libsystem_platform.dylib 0x000000019c7b42a4 _sigtramp + 56
4  swift-frontend           0x0000000102feb69c llvm::DwarfExpression::addExpression(llvm::DIExpressionCursor&&, llvm::function_ref<bool (unsigned int, llvm::DIExpressionCursor&)>) + 124
5  swift-frontend           0x0000000102fcd624 llvm::DwarfDebug::emitDebugLocValue(llvm::AsmPrinter const&, llvm::DIBasicType const*, llvm::DbgValueLoc const&, llvm::DwarfExpression&) + 716
6  swift-frontend           0x0000000102fca624 llvm::DwarfDebug::endFunctionImpl(llvm::MachineFunction const*) + 6564
7  swift-frontend           0x0000000102fae0b0 llvm::DebugHandlerBase::endFunction(llvm::MachineFunction const*) + 100
8  swift-frontend           0x0000000102f91918 llvm::AsmPrinter::emitFunctionBody() + 15144
9  swift-frontend           0x00000001029202dc llvm::X86AsmPrinter::runOnMachineFunction(llvm::MachineFunction&) + 488
10 swift-frontend           0x000000010395e164 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 308
11 swift-frontend           0x0000000105dd9150 llvm::FPPassManager::runOnFunction(llvm::Function&) + 1320
12 swift-frontend           0x0000000105de139c llvm::FPPassManager::runOnModule(llvm::Module&) + 60
13 swift-frontend           0x0000000105dd9ed0 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 2424
14 swift-frontend           0x00000001014c638c swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, swift::UnifiedStatsReporter*) + 3800
15 swift-frontend           0x00000001014d9b70 (anonymous namespace)::LLVMCodeGenThreads::Thread::run() + 148
16 swift-frontend           0x00000001014d9ad0 (anonymous namespace)::LLVMCodeGenThreads::runThread(void*) + 12
17 libsystem_pthread.dylib  0x000000019c78606c _pthread_start + 148
18 libsystem_pthread.dylib  0x000000019c780e2c thread_start + 8
Command SwiftCompile failed with a nonzero exit code
```

**Comment by NachoSoto** [comment]
Thanks for the report, this looks like a Swift bug but I can help you work around it.

Can you provide a bit more info?
- What does your project look like
- How are you integrating the SDK (CocoaPods / SPM, etc)
- Complete Xcode build log, what command is it running when this crashed?
- Are you building for debug or release?
- Do you have any non-standard flags, like different optimization settings?
- Have you tried clearing derived data and trying again?

**Comment by NachoSoto** [comment]
I also recommend what the error suggests and filing this to Swift itself: https://swift.org/contributing/#reporting-bugs

**Comment by jesus-mg-ios** [comment]
Thanks @NachoSoto, it's SPM. I'm gonna try to directly link the xcframework that it's posted on the release tag. If it doesn't work (that should work) I'll fill you all the bullet points. Also I will send the bug to swift.

Thanks for the support

**Comment by jesus-mg-ios** [comment]
@NachoSoto I was asking why the xcframework zip attached on release tag has other things like archives.

**Comment by jesus-mg-ios** [comment]
Closing this, because the bug was reported to Apple
