### ISSUE TITLE
"SNAPSHOT" in version

### ISSUE THREAD

**Issue by XericDesign** [RevenueCat/purchases-ios#245]
With 3.3.0 I am seeing:
DEBUG: SDK Version - 3.3.0-SNAPSHOT

Under 3.2.2 I am seeing:
DEBUG: SDK Version - 3.2.2

What is the significance of "SNAPSHOT" in the version description? Did this not come from the main branch and is this an official release version?

**Comment by aboedo** [comment]
Hi! Sorry for the confusion. It is an official release, 3.3.0. 

We use the suffix `-SNAPSHOT` to indicate development versions, and when making a release, we remove the `-SNAPSHOT`... But we missed it in a couple of files this time around. 

I'll make a 3.3.1 release tomorrow morning to fix the version numbers and remove any confusion, but in the meantime, no need to worry, that's an official release version.

**Comment by aboedo** [comment]
released 3.3.1, it's identical to 3.3.0 but with the suffix fixed, sorry again for the confusion!
