### ISSUE TITLE
Error on sandbox test user 

### ISSUE THREAD

**Issue by jesus-mg-ios** [RevenueCat/purchases-ios#2465]
- [ ] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: Simulator iOS
   2. SDK version: 4.17.9
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N): default
   4. OS version: iOS 16.4
   5. Xcode version: 14.3.0
   6. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```
Product purchase for 'product_id' failed with error: 
Error Domain=RevenueCat.ErrorCode Code=16 "There was an unknown backend error. 

The subscriber has reached the max number of Apple receipts allowed (100). (7636)"
 UserInfo={source_file=RevenueCat/HTTPClient.swift:410, rc_backend_error_code=7636, 
source_function=convertUnsuccessfulResponseToError(),
 NSUnderlyingError=0x600001c44750 {Error Domain=RevenueCat.BackendErrorCode Code=-1 
"The subscriber has reached the max number of Apple receipts allowed (100). 

(7636)" UserInfo={rc_backend_error_code=7636, 
NSLocalizedDescription=The subscriber has reached the max number of Apple receipts allowed (100). (7636)}}, NSLocalizedDescription=There was an unknown backend error. 

The subscriber has reached the max number of Apple receipts allowed (100). (7636), rc_response_status_code=400, readable_error_code=UNKNOWN_BACKEND_ERROR}
```
4. Steps to reproduce, with a description of expected vs. actual behavior
5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
This error appears when I tried to purchase on UI Test with a specific user. How can I resolve it?

**Comment by HaleyRevcat** [comment]
Hi,

You are getting the error "The subscriber has reached the max number of Apple receipts allowed" because we only allow a max of 100 receipts to prevent an excess of transactions if many users are using the same app user id. Try deleting the user from RevenueCat, and setting up a new sandbox test account and Apple ID: https://www.revenuecat.com/docs/apple-app-store#create-a-sandbox-test-account. 

Normally users in production do not hit this 100 receipt limit, but if they do you can contact us and we can assist.

**Comment by jesus-mg-ios** [comment]
@HaleyRevcat, thanks for your reply. Is it possible to remove the limit in sandbox environment?

Thanks

**Comment by HaleyRevcat** [comment]
No, it is not possible to remove this limit from sandbox at this time. This is because sandbox testing can generate a lot of receipts and this may result in performance issues.

**Comment by jesus-mg-ios** [comment]
And, maybe Could you use a workaround to get the last x receipts to validate, instead of validating each one or processing them?
