### ISSUE TITLE
Rejected by Apple for Kid Category

### ISSUE THREAD

**Issue by cp3hnu** [RevenueCat/purchases-ios#257]
RevenueCat is great, but my app is rejected by Apple for Kid Category.
First, Apple ask the following questions and my answers where app review.
• Does your app include third-party analytics? If so, please provide details about what data is collected for this purpose.
No
• Does your app include third-party advertising? If so, please provide a link to the ad network's publicly-documented practices and policies for kids apps.
No
• Will the data be shared with any third parties? If so, for what purposes and where will this information be stored?
No
• Is your app collecting any user or device data for purposes beyond third-party analytics or third-party advertising? If so, please provide a complete and clear explanation of all planned uses of this data.
No
Then,  my app is rejected because
"We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties.
Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:
Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA."

My app doesn't have any network requests except IAP.
What suggestions do you have for replying to Apple? Thank you.

**Comment by aboedo** [comment]
Hi! 
We've seen this happen in the past when developers add the `AdSupport` framework to the project, or when adding other libraries. 
purchases-ios doesn't actually use the IDFA unless the `AdSupport` framework is included. 

Are you using frameworks other than RevenueCat? Also, is `AdSupport` linked in the Framework and Libraries tab for your project?

**Comment by cp3hnu** [comment]
I do not use AdSupport framework and other frameworks. My app is online by removing RevenueCat framework, but I wish I could get it back.

**Comment by rkotzy** [comment]
@cp3hnu can you send an email to support@revenuecat.com with details about your app? We work with other Kids apps and it's an important category for us - RevenueCat is COPPA compliant out-of-the-box specifically for this reason (we even drop IP address from our logs since it's identifiable information).

We haven't heard of this specific rejection before but would want to make sure there is a workaround.

**Comment by cp3hnu** [comment]
OK, Thank you for your reply.

**Comment by aboedo** [comment]
@cp3hnu did you manage to get this solved?

**Comment by cp3hnu** [comment]
No, I didn't try again.

**Comment by rkotzy** [comment]
Going to go ahead and close this out unless we get more reports of this and can re-open. There have been other Kids apps to recently launch with RevenueCat - this may have been a case from a specific reviewer.
