### ISSUE TITLE
Static Analyzer reports 5 warnings in RCProductInfoExtractor.m: nil returned from a method that is expected to return a non-null value

### ISSUE THREAD

**Issue by Timac** [RevenueCat/purchases-ios#264]
**Steps to reproduce:**

- Open the Purchases.xcodeproj project in Xcode 11.5
- Choose for target an iPhone 11 Pro Simulator
- Perform a static analysis with Product > Analyze

**Result:**
You see 5 warnings in `RCProductInfoExtractor.m` "nil returned from a method that is expected to return a non-null value":

<img width="449" alt="screenshot" src="https://user-images.githubusercontent.com/738543/85200542-9c2c3d80-b2f8-11ea-9e5d-4a43af41d096.png">

**Comment by Timac** [comment]
A pull request has been submitted: #265

**Comment by aboedo** [comment]
Hi @Timac! Thanks for reporting and posting the PR!

**Comment by aboedo** [comment]
Closing because the PR was merged. Thanks again!
