### ISSUE TITLE
Bad version number

### ISSUE THREAD

**Issue by XericDesign** [RevenueCat/purchases-ios#277]
The version number in the 3.5.0 framework build for tvOS is "3.6.0-SNAPSHOT". This causes an error when uploading to the AppStore:

ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.6.0-SNAPSHOT

**Comment by aboedo** [comment]
Hi @XericDesign, I apologize for the inconvenience, I'll get that fixed right away

**Comment by aboedo** [comment]
I updated the release. This should be fixed.
