### ISSUE TITLE
Linker errors ("Undefined symbol") in Xcode 11.6 with RC 3.4/3.5

### ISSUE THREAD

**Issue by michaellenaghan** [RevenueCat/purchases-ios#282]
I upgraded to Xcode 11.6 last night. I got the following linker errors in RC 3.4 on my first Xcode 11.6 build attempt. They persisted after I upgraded to RC 3.5. I'm using RC from within a local Swift package.

Here's the last part of the error:

```
Undefined symbols for architecture x86_64:
  "___ubsan_handle_nonnull_arg", referenced from:
      -[RCPurchaserInfo setUpDateFormatter] in Purchases.o
      -[RCPurchases dispatch:] in Purchases.o
  "___ubsan_handle_float_cast_overflow", referenced from:
      -[NSDate(RCExtensions) millisecondsSince1970] in Purchases.o
  "___ubsan_handle_load_invalid_value", referenced from:
      _RCSetShowDebugLogs in Purchases.o
      _RCShowDebugLogs in Purchases.o
      _RCDebugLog in Purchases.o
      _RCErrorLog in Purchases.o
      -[RCSystemInfo initWithPlatformFlavor:platformFlavorVersion:finishTransactions:] in Purchases.o
      -[RCSystemInfo finishTransactions] in Purchases.o
      -[RCSystemInfo setFinishTransactions:] in Purchases.o
      ...
  "___ubsan_handle_pointer_overflow", referenced from:
      ___32-[NSData(RCExtensions) asString]_block_invoke in Purchases.o
  "___ubsan_handle_type_mismatch_v1", referenced from:
      -[RCInMemoryCachedObject setCacheDurationInSeconds:] in Purchases.o
      ___32-[NSData(RCExtensions) asString]_block_invoke in Purchases.o
      -[RCSystemInfo setFinishTransactions:] in Purchases.o
      -[RCHTTPClient setSystemInfo:] in Purchases.o
      -[RCIntroEligibility setStatus:] in Purchases.o
      -[RCPurchaserInfo setUpDateFormatter] in Purchases.o
      -[RCPurchases allowSharingAppStoreAccount] in Purchases.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm still looking into this but thought it might be worth flagging right away.

**Comment by michaellenaghan** [comment]
As I look into this, a relevant detail, I think: I was building for testing.

**Comment by michaellenaghan** [comment]
OK, I'll close this. :-)

I think the Xcode 11.6 bit was irrelevant. Long story short(ish): I hadn't added the module that contained RC to my test scheme, and one of my test scheme configurations turned on UBSan. I think that since there was no test-built RC module Xcode was falling back on the regular debug-build RC module, and that module wasn't built with UBSan.

I'm not sure that that's right, but I think it's in the ballpark. I'm still poking around, but the main result so far is that I don't think it's an Xcode 11.6-based problem.

**Comment by michaellenaghan** [comment]
I closed this, but I tracked down the problem and the cause may be relevant to others. The short version is that there are several problems using test plans and test configurations with Swift (local) packages. I reported the bug here:

    https://developer.apple.com/forums/thread/133495

Apple confirmed and logged it.

**Comment by aboedo** [comment]
sounds like that must have been a tough debugging session. Thanks for reporting and for posting the workaround! I'm sure it'll help others.
