### ISSUE TITLE
Warning with Xcode 12: enumeration values 'SKErrorOverlayCancelled', 'SKErrorOverlayInvalidConfiguration', and 'SKErrorOverlayTimeout' not handled in switch

### ISSUE THREAD

**Issue by Timac** [RevenueCat/purchases-ios#292]
**Description**
If you compile the project with Xcode 12 beta 3 with a deployment target set to iOS 14, you will see a warning

```
enumeration values 'SKErrorOverlayCancelled', 'SKErrorOverlayInvalidConfiguration', and 'SKErrorOverlayTimeout' not handled in switch
```

**Steps to reproduce:**

1. Open the Purchases.xcodeproj project in Xcode 12.0 beta 3
2. Set the iOS deployment target to iOS 14
3. Compile the project

**Result:**
You see a warning
```
enumeration values 'SKErrorOverlayCancelled', 'SKErrorOverlayInvalidConfiguration', and 'SKErrorOverlayTimeout' not handled in switch
```

<img width="1418" alt="screenshot" src="https://user-images.githubusercontent.com/738543/88456329-13676b00-ce7d-11ea-92f0-f7fb53194e43.png">

**Environment**
    1. Platform: iOS
    2. SDK version: iOS 14
    3. OS version: macOS 10.15.6
    4. Xcode version: Xcode 12.0 beta 3 (12A8169g)

**Comment by aboedo** [comment]
hi! thanks for reporting. We'll get those added.

**Comment by aboedo** [comment]
sorry for the delay, this has been addressed in https://github.com/RevenueCat/purchases-ios/pull/334

**Comment by aboedo** [comment]
@Timac 3.7.0 has shipped with the new SKErrors! Closing this now. Thanks again for reporting!
