### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by JMCPH** [RevenueCat/purchases-ios#300]
**Describe the bug**
There is an issue in the latest framework version. UI API was called on a background thread on the line RCSystemInfo.m - 87.

1. Environment
    1. Platform: iOS
    2. SDK version: 3.5.2
    3. OS version: 13.5.1
    4. Xcode version: 11.6
    5. How widespread is the issue. Percentage of devices affected: 100 %
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

```
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 908, TID: 139231, Thread name: (none), Queue name: NSOperationQueue 0x10bc0fdf0 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   Purchases                           0x0000000105611a9c -[RCSystemInfo isApplicationBackgrounded] + 88
5   Purchases                           0x00000001055ff748 -[RCPurchases initWithAppUserID:requestFetcher:receiptFetcher:attributionFetcher:backend:storeKitWrapper:notificationCenter:userDefaults:systemInfo:offeringsFactory:deviceCache:identityManager:subscriberAttributesManager:] + 1500
6   Purchases                           0x00000001055feffc -[RCPurchases initWithAPIKey:appUserID:userDefaults:observerMode:platformFlavor:platformFlavorVersion:] + 912
7   Purchases                           0x00000001055feb00 +[RCPurchases configureWithAPIKey:appUserID:observerMode:userDefaults:platformFlavor:platformFlavorVersion:] + 244
8   Purchases                           0x00000001055fe9c8 +[RCPurchases configureWithAPIKey:appUserID:observerMode:userDefaults:] + 176
9   Purchases                           0x00000001055fe8e0 +[RCPurchases configureWithAPIKey:appUserID:observerMode:] + 136
```

3. Steps to reproduce, with a description of expected vs. actual behavior
`Purchases.configure(withAPIKey: "XXXX", appUserID: userID, observerMode: true)`

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by JMCPH** [comment]
@aboedo can you please take a look at this? We are planning to start paying from next week, so we are really hoping you can take a quick look at this :)

**Comment by aboedo** [comment]
I was actually looking at rewriting that method for a different reason (app extensions), so I'll take the opportunity to fix this as well

**Comment by JMCPH** [comment]
Awesome, let me know when it's done 👍🏼

**Comment by aboedo** [comment]
update here: https://github.com/RevenueCat/purchases-ios/pull/303 contains the fix and has been merged, this will be shipped in the next release.

**Comment by JMCPH** [comment]
@aboedo thank you
