### ISSUE TITLE
checkTrialOrIntroductoryPriceEligibility:completionBlock does not call completion block on old OS versions

### ISSUE THREAD

**Issue by density** [RevenueCat/purchases-ios#341]
**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Environment
    1. Platform: iOS
    2. SDK version: 13
    3. OS version: any version < 12
    4. Xcode version: 11.7
    5. How widespread is the issue. Percentage of devices affected. Probably not many
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: N/A
3. Steps to reproduce, with a description of expected vs. actual behavior

Relevant line of code here: https://github.com/RevenueCat/purchases-ios/blob/800fa6b561777a26f01d33dd8a9ae509403b9b32/Purchases/Public/RCPurchases.m#L629

The `checkTrialOrIntroductoryPriceEligibility:completionBlock` correctly guards the eligibility calculation with an `@available` check. However, when this guard evaluates to false (e.g., on iOS 9), it falls through to the end of the `if (data != nil && data.length > 0)` and does NOT call the `completionBlock`, which could cause the caller to hang forever.

Instead, the `completionBlock` should be called with `RCIntroEligibilityStatusUnknown` since old OSes don't support intro pricing anyway. Alternatively, it could try to fetch the eligibility from the backend like it does in the `else` branch.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

N/A

**Comment by aboedo** [comment]
you're right! thanks for reporting this, we'll get a fix out ASAP

**Comment by aboedo** [comment]
the fix will go into a patch 3.6.1 release and in 3.7.0, both of which will likely be released between today and tomorrow

**Comment by aboedo** [comment]
The fix made it into releases 3.6.1 and 3.7.0, and both of them are out 🎉 @density thanks again for reporting! Closing this as solved.
