### ISSUE TITLE
iOS 14 - offerings.current is nil in simulator (but everything is fine on iOS 13)

### ISSUE THREAD

**Issue by Gurbo** [RevenueCat/purchases-ios#357]
iOS 14 - offerings.current is nil in simulator (but everything is fine on iOS 13).

2020-09-26 12:23:34.110686+0300 ______[6372:297080] [Purchases] - DEBUG: SKRequest failed: UNKNOWN_ERROR
2020-09-26 12:23:34.111091+0300 ______[6372:296847] [Purchases] - INFO: Could not find SKProduct for (
    "______",

**Comment by jhk115** [comment]
Glad I checked Github issues! Confirming this is the case.

**Comment by aboedo** [comment]
Hi! Thanks for opening. 
This is unfortunately expected now - we'll update our docs accordingly. 
As of iOS 14, simulators won't load products unless you're using StoreKit Config Files. However, doing so will cause purchases to be signed with a different certificate, which will fail validation when synced with our backend. 

We're currently working on adding support for it backend-side, however for the time being we recommend either testing with a physical iOS 14 device or an iOS 13 simulator. 
Note that although the iOS 13 simulator loads products correctly, it doesn't allow for purchases to be made.
