### ISSUE TITLE
Swift file breaks rile naming rules on certain platforms

### ISSUE THREAD

**Issue by matej** [RevenueCat/purchases-ios#361]
**Describe the bug**

I just broke Git checkouts four our Windows clients when committing a RevenueCat update to the iOS portion of our monorepo. 

Specifically those two files break Windows file naming rules:
- https://github.com/RevenueCat/purchases-ios/blob/develop/PurchasesCoreSwift/LocalReceiptParsing/DataConverters/ArraySlice%3CUInt8%3E+Extensions.swift
- https://github.com/RevenueCat/purchases-ios/blob/develop/PurchasesCoreSwiftTests/LocalReceiptParsing/DataConverters/ArraySlice%3CUInt8%3E+ExtensionsTests.swift

I solved this by removing the offending characters (`<` `>`) and using `ArraySlice-UInt8+Extensions.swift` as the file name instead. I'd recommend that you do something similar to make updates easier for repositories with shared code. 

1. Environment
    1. Platform: iOS
    2. SDK version: 3.7.2
    3. OS version: Windows 10
    4. Xcode version: Not relevant.
    5. How widespread is the issue. Percentage of devices affected: Not relevant.

2. Steps to reproduce, with a description of expected vs. actual behavior

Try checking out your repo on a Windows machine. You should get an error. Here's the one we got:

```
git pull
...
error: invalid path 'iOS/Viewer/Vendor/RevenueCat/PurchasesCoreSwift/LocalReceiptParsing/DataConverters/ArraySlice<UInt8>+Extensions.swift'
```

Instead it should just work.

3. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

More info on this topic: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file. We'll be implementing Danger checks to check for safe file names in the future. You could consider the same.

**Comment by aboedo** [comment]
Thanks for reporting! I'll update the file names.

**Comment by aboedo** [comment]
@matej version 3.7.3 has been released and includes the file name fix. Thanks again for reporting!

**Comment by matej** [comment]
Thank you for fixing it so quickly!
