### ISSUE TITLE
[macOS] Purchases.purchasePackage returns userCancelled == false when clicking on Cancel in Confirm Subscription popup

### ISSUE THREAD

**Issue by ignalonzo** [RevenueCat/purchases-ios#369]
## Common project specific issues

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Environment
    1. Platform: macOS 
    2. SDK version: 10.15.6 (19G68)
    3. OS version: 11.0 (Big Sur)
    4. Xcode version: 12.0.1
    5. How widespread is the issue. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) 

`<SKPaymentQueue: 0x6000015cd740>: Payment completed with error: Error Domain=ASDServerErrorDomain Code=5115 "The server encountered an error" UserInfo={NSLocalizedDescription=The server encountered an error}
[Purchases] - DEBUG: PaymentQueue updatedTransaction: P1Y.mac_app_store_trial_1 (null) (Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x6000018cd260 {Error Domain=ASDServerErrorDomain Code=5115 "The server encountered an error" UserInfo={NSLocalizedDescription=The server encountered an error}}}) (null) - 2
[Purchases] - ERROR: There was a problem with the App Store.`

3. Steps to reproduce, with a description of expected vs. actual behavior

#### Steps to reproduce: 
1. Click on Cancel in either the Subscription Terms screen or Confirm Subscription screen 

![image](https://user-images.githubusercontent.com/43062515/95954128-81c82380-0e03-11eb-82ad-193182ae5939.png)

![image](https://user-images.githubusercontent.com/43062515/95954202-9ad0d480-0e03-11eb-9a6a-36827421a943.png)

#### Expected outcome:

- Returns 'userCancelled == true'

#### Actual:

- Returns `userCancelled == false` and error:

![image](https://user-images.githubusercontent.com/43062515/95954371-dd92ac80-0e03-11eb-9037-d80e35e66c90.png)

**Comment by NikKovIos** [comment]
The same error. What did you do with it?
