### ISSUE TITLE
[Crash] leaves the SDK in an undetermined state

### ISSUE THREAD

**Issue by yuratrotskyi** [RevenueCat/purchases-ios#375]
I am running my app with Purchases SDK v3.7.4 and get a crash if I delete my app with your SDK and running again on the same device (simulator or real device) only for the first time.
 
I got this type of error
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[Purchases] - Cached appUserID has been deleted from user defaults. This leaves the SDK in an undetermined state. Please make sure that RevenueCat entries in user defaults don't get deleted by anything other than the SDK. More info: https://support.revenuecat.com/hc/en-us/articles/360047927393'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.0.2 - Device: iPhone 11 (FE5DEB3A-850B-4262-8163-E81D581CA4CD) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11
Xcode version: 12.0.1 (12A7300)

Way to configure SDK: 
Purchases.configure(withAPIKey: *my_API_key*,
                                    appUserID: UIDevice.current.identifierForVendor?.uuidString)

*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20439f4f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207881ca -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Reshape                             0x00000001058bb097 -[RCDeviceCache handleUserDefaultsChanged:] + 343
	5   CoreFoundation                      0x00007fff2037bc46 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff2037bc15 ___CFXRegistrationPost_block_invoke + 49
	7   CoreFoundation                      0x00007fff2037b333 _CFXRegistrationPost + 454
	8   CoreFoundation                      0x00007fff2037aca1 _CFXNotificationPost + 796
	9   Foundation                          0x00007fff207fc3ba -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	10  Reshape                             0x00000001050e372c -[AFSDKUserDefaultsStorage setString:forKey:] + 148
	11  Reshape                             0x00000001050f580a -[AppsFlyerTracker resolveOriginalAppsFlyerID:] + 1320
	12  Reshape                             0x00000001050f52c5 __42-[AppsFlyerTracker getOriginalAppsFlyerId]_block_invoke + 28
	13  libdispatch.dylib                   0x000000010ce55a88 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010ce56ff3 _dispatch_once_callout + 66
	15  Reshape                             0x00000001050f52a7 -[AppsFlyerTracker getOriginalAppsFlyerId] + 97
	16  Reshape                             0x00000001050ec576 __24-[AppsFlyerTracker init]_block_invoke + 69
	17  libdispatch.dylib                   0x000000010ce548ac _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x000000010ce55a88 _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010ce5c356 _dispatch_lane_serial_drain + 796
	20  libdispatch.dylib                   0x000000010ce5d027 _dispatch_lane_invoke + 439
	21  libdispatch.dylib                   0x000000010ce68e90 _dispatch_workloop_worker_thread + 882
	22  libsystem_pthread.dylib             0x00007fff5dcd8a3d _pthread_wqthread + 290
	23  libsystem_pthread.dylib             0x00007fff5dcd7b77 start_wqthread + 15
)

after the second run, everything is okay

**Comment by aboedo** [comment]
Hi 👋 thanks for reporting. 

I think this might be happening as a result of a race condition, where `RCDeviceCache` sets up and starts observing changes to `NSUserDefaults`, but it may not have an appUserID yet. We'll get it fixed.

**Comment by yuratrotskyi** [comment]
Hi 👋 , thanks for the quick response!
Looking forward to the new version with fixed issue

**Comment by aboedo** [comment]
the fix has been merged and released in 3.7.6 🎉 
Thanks @yuratrotskyi for reporting!

**Comment by norrisboat** [comment]
@aboedo I'm experiencing this on 3.11.1
