### ISSUE TITLE
purchases-ios stuck fetching in Xcode

### ISSUE THREAD

**Issue by pnome** [RevenueCat/purchases-ios#3770]
I frequently hit an issue in Xcode with the purchases-ios package. It gets stuck in the fetching... state. I can't understand why. I have about 20 packages and none of the others have an issue. I also use PurchasesHelper which also gets stuck. 

I removed both RevenueCat and PurchasesHelper, cleared caches and derived data.  All the other packages installed ok.

I then reinstalled RevenueCat and it seemed to work.
Then I tried to install PurchasesHelper and it got stuck in the "Starting package resolution" phase.
I tried Reset Package Caches in Xcode and all packages sorted themselves out apart from purchases-ios which got stuck again in the "fetching" state.

If I close Xcode and run
rm -rf ~/Library/Caches/org.swift.swiftpm ~/Library/Developer/Xcode/DerivedData ~/Library/org.swift.swiftpm ~/.swiftpm/xcode/

Then reopen, purchases-ios is the only package that gets stuck in the fetching state.
I cannot figure out why this would be the case.

   4. OS version: Sonoma 14.0
   5. Xcode version: 15.3

**Comment by pnome** [comment]
Update...
I went to install purchases-ios again. It was stuck in the fetching state for 5 minutes. Then it got stuck at 44% for a few mins. Then it seemed to start over multiple times.
It finally installed after 10 minutes.  Surely that isn't normal.

I tried to install PurchasesHelper next and it just stalls at Starting Package Resolution.

I'm downloading Xcode 15.2 to see if that helps.

For the record, I've had both purchases-ios and PurchasesHelper installed as packages for a couple of years.  I have noticed in the past that those 2 are the ones most likely to get stuck, but it's never been this bad.

Any insight into why those two packages would get stuck when nothing else does is much appreciated.

**Comment by pnome** [comment]
Further update...
I downloaded and installed Xcode 15.2 (the above was all happening in 15.3)
I went to install PurchasesHelper package. In the Verifying PurchasesHelper stage I saw that it fetched all of the other packages I had installed. 
When it got to purchases-ios, it got to 44% in a minute, then crawled up extremely slowly. It was 46% a couple of minutes later. Again, it took nearly 10 minutes to fetch it.

Something is wrong there, I'm sure.

**Comment by mshmoustafa** [comment]
Hey @pnome 
That's super strange but we've seen strange bugs and glitches with SPM before so it's not super surprising. It's usually due to some bug in Xcode. It could be due to how SPM downloads the git repository also: https://forums.swift.org/t/why-is-fetching-dependencies-with-swiftpm-so-slow/67191
