### ISSUE TITLE
`purchasePackage` completion handler not called on _cancel_

### ISSUE THREAD

**Issue by jasonzurita** [RevenueCat/purchases-ios#378]
**Describe the bug**
When attempting to make a purchase, I am noticing that the `Purchases.shared.purchasePackage` completion handler isn't called if the initial popup is dismissed via cancel button (see below for screenshots of the popups). This is happening in both debug and in production builds, and is currently in production with this issue.

In addition to this being unexpected behavior, an issue is that in this scenario there is no way to know when to re-enable UI interaction (e.g., buttons, spinners, etc.) after the user has tapped to make a purchase.

_Initial popup_ (pressing cancel on this screen doesn't result in the completion handler being called)
Debug build (sandbox testing)
<img src="https://user-images.githubusercontent.com/13800855/97209619-f2235d00-1792-11eb-8612-e9145e9b7271.png" width=250 />

Production build
<img src="https://user-images.githubusercontent.com/13800855/97208546-a0c69e00-1791-11eb-9532-dad62161a8f4.png" width=250 />

---

1. Environment
    1. Platform: watchOS
    2. SDK version: 3.7.4
    3. OS version: 7.0.2
    4. Xcode version: 12.1
    5. How widespread is the issue. Percentage of devices affected. _All devices as far as I can tell._

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
  - 2020-10-26 12:25:57.981512-0400 WatchKit Extension[1489:1596014] [Purchases] - DEBUG: makePurchase
  - 2020-10-26 12:25:57.992022-0400 WatchKit Extension[1489:1596014] [Purchases] - DEBUG: makePurchase - com.promonthly - Offering: default
  - None after pressing the **Cancel** button from either of the above screens. I would expect to see something here.

3. Steps to reproduce, with a description of expected vs. actual behavior
- Call `purchasePackage`
- Press _cancel_ when at the screenshots above
- Completion handler not called

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
    None.

**Additional context**
Also for some reason, I am seeing a ton (~50) of these debug logs that need to finish being reported out to the console before I am able to try and place an order (this takes around 15s):
```
2020-10-26 12:16:31.591464-0400 WatchKit Extension[1487:1589691] [Purchases] - DEBUG: PaymentQueue removedTransaction: com.promonthly 1000000690419276 (1000000689222985 (null)) (null) - 1
```

**Comment by rkotzy** [comment]
The 50+ `removedTransaction` logs indicate the the receipt may have 50+ unfinished transactions and the SKPaymentQueue is really slow. Maybe these were from purchases before using RevenueCat? Can you try with a new sandbox user and confirm you are not setting `finishTransactions=false`?

The userCancelled error is relayed directly from Apple. If you put a breakpoint in RCPurchases.m in the [storekit wrapper updated transaction method](https://github.com/RevenueCat/purchases-ios/blob/abcc7148c10105f57f7d8f51be931e39f51734df/Purchases/Public/RCPurchases.m#L1066), what is the `transaction.error.code` that Apple is returning? 

![Screen Shot 2020-10-26 at 12 48 13 PM](https://user-images.githubusercontent.com/1294361/97221022-9bfdec00-1789-11eb-9854-93571ad73fdc.png)

**Comment by jasonzurita** [comment]
> The 50+ removedTransaction logs indicate the the receipt may have 50+ unfinished transactions and the SKPaymentQueue is really slow. Maybe these were from purchases before using RevenueCat? Can you try with a new sandbox user and confirm you are not setting finishTransactions=false?

Ahh, interesting. These purchases were only made using RevenueCat.  I will also give a new sandbox user a try to see if things change.

Also, something that is weird with this is that I see this queue flushing out every time the app starts up. Seems like it should flush out once and be done, but for some reason that isn't the case.

> The userCancelled error is relayed directly from Apple. If you put a breakpoint in RCPurchases.m in the storekit wrapper updated transaction method, what is the transaction.error.code that Apple is returning?

Just tried adding this breakpoint. It hit when pressing the purchase button (no error as expected), but got nothing when pressing cancel on that initial popup :(.

**Comment by rkotzy** [comment]
>Also, something that is weird with this is that I see this queue flushing out every time the app starts up. Seems like it should flush out once and be done, but for some reason that isn't the case.

The queue should flush out unless the SDK is configured in observer mode or `finishTransactions` is set to `false`.

**Comment by jasonzurita** [comment]
> The queue should flush out unless the SDK is configured in observer mode or finishTransactions is set to false.

Interesting. I will do some more tests and file a separate issue if things still don't seem to be flushing out as expected.

---

Anything else to try or check for the main part of this issue?

**Comment by rkotzy** [comment]
This actually may be a simulator issue as well. Does it reproduce if you run it on an actual watch? 

If StoreKit is not providing any failure or completion state, then the completion block from RevenueCat will never fire either. There may be some more clues in the full debug log output (e.g. if two instances of the SDK are being configured you may be purchasing from one instance and listening for the completion block on another). If you don't want to post the entire output here, you can create a support ticket with those details.

**Comment by jasonzurita** [comment]
> This actually may be a simulator issue as well. Does it reproduce if you run it on an actual watch?

I have only tried this on a real device.

> If StoreKit is not providing any failure or completion state, then the completion block from RevenueCat will never fire either. There may be some more clues in the full debug log output (e.g. if two instances of the SDK are being configured you may be purchasing from one instance and listening for the completion block on another). If you don't want to post the entire output here, you can create a support ticket with those details.

Interesting thought! I will dig into that a little. I am listening to the _purchase_ request and response with the same instance of the SDK (in the same module).

Would this be an elevated log level to turn on, or are you referring to the already printing out debug log?

**Comment by rkotzy** [comment]
>Would this be an elevated log level to turn on, or are you referring to the already printing out debug log?

There is an elevated level of informational logging that may provide some more context. You can enable this by setting `Purchases.debugLogsEnabled = true` before configuration.

**Comment by jasonzurita** [comment]
> > Would this be an elevated log level to turn on, or are you referring to the already printing out debug log?
> 
> There is an elevated level of informational logging that may provide some more context. You can enable this by setting `Purchases.debugLogsEnabled = true` before configuration.

Sorry for the delay @rkotzy. Ahh, yes I have that enabled in debug builds! Below is the full debug log output (some minor redacting). Note: At the very end of the logs, I start a purchase and press cancel on that initial popup as previously described. Nothing ends up being logged out based on that action.

[iap_logs.txt](https://github.com/RevenueCat/purchases-ios/files/5468469/iap_logs.txt)


Please let me know what else I can do to help figure this out!

**Comment by rkotzy** [comment]
With all of those transactions on the payment queue, it could just be taking a _looong_ time for Apple to return some completed state for the purchase. I would try with a new sandbox user - they will have a new receipt and shouldn't have any updated transactions on the payment queue.

**Comment by jasonzurita** [comment]
> With all of those transactions on the payment queue, it could just be taking a _looong_ time for Apple to return some completed state for the purchase. I would try with a new sandbox user - they will have a new receipt and shouldn't have any updated transactions on the payment queue.

I have tried this in production with my real Apple ID where I don't have all of those transactions on the payment queue, and I still get this issue.

**Comment by jasonzurita** [comment]
Any update on this @rkotzy?

**Comment by jasonzurita** [comment]
Any update on this @rkotzy?

**Comment by aboedo** [comment]
Is this happening only on apple watch? If so, maybe it's a bug specific to watchOS. @jasonzurita do you have an iOS app as well or is it watch-only? 

@alamodey is `configure` getting called at all for you? If so, then your case might be a different issue. 

Inside `configure`, which `purchaserInfo` are you using? Is it the latest one from the delegate, are you calling the `purchaserInfo` method again, or something else? 
Note that `purchasePackage`'s callback already sends in a purchaserInfo, so you could just call it sending in the purchaserInfo, as in `configure(withPurchaserInfo: purchaserInfo)`. Otherwise, you could set up the delegate to automatically call configure whenever the `purchaserInfo` is updated.
