### ISSUE TITLE
SKReceiptRefreshRequest background task not terminating despite a successful completion

### ISSUE THREAD

**Issue by xsleonard** [RevenueCat/purchases-ios#391]
This is almost the same as #250, but the request type is different (`SKReceiptRefreshRequest`), and there aren't networking issues on the device that I'm aware of. The warning shows up after the completion handler for `restoreTransactions` has finished successfully.

> [BackgroundTask] Background Task 61 ("SKReceiptRefreshRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

- Purchases v3.7.6
- iOS 14.0
- Real device, attached to xcode. 
- Sandbox

**Comment by rkotzy** [comment]
I think this is similar to #250, the `SKReceiptRefreshRequest` is managed by iOS and the Purchases SDK can only call `start` on the task. Can you confirm @aboedo?

**Comment by aboedo** [comment]
actually, although it looks very similar from the outside, I think this is a separate thing. 
I'm debugging it and I can 100% reproduce, I believe that the SDK may have a leak where the `SKReceiptRefreshRequest` doesn't get dealloc'ed, and this warning is issued even though the request is actually done. 
@xsleonard thanks for reporting!

**Comment by aboedo** [comment]
it might actually be an iOS bug, if I call `cancel` on the request after it's finished, the warning disappears and the request gets dealloc'ed correctly

**Comment by bixcorp** [comment]
Same for me.
- Purchases v3.7.5
- iOS 14.2
- iOS Simulator, attached to xcode.
- Sandbox

**Comment by smohn** [comment]
+1

**Comment by aboedo** [comment]
3.9.2 is out with the fix! Closing now. Thanks again for reporting!
