### ISSUE TITLE
Making a purchase in airplane mode returns unknown error instead of network error

### ISSUE THREAD

**Issue by xsleonard** [RevenueCat/purchases-ios#396]
With the device in airplane mode, attempting to purchase returns "unknown error" instead of a network error. The underlying error suggests that this could be handled as a network error:

> ERROR: purchasePackageFailed(error:) purchasePackage failed: Error Domain=RCPurchasesErrorDomain Code=0 "Unknown error." UserInfo={readable_error_code=UNKNOWN, NSLocalizedDescription=Unknown error., NSUnderlyingError=0x282fd7ed0 {Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSLocalizedDescription=The Internet connection appears to be offline., NSUnderlyingError=0x282fd6eb0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1009.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1009.)}}}}}

- Purchases 3.7.6
- Real device, attached to xcode
- Sandbox

**Comment by xsleonard** [comment]
On a subsequent attempt about an hour later, under the same conditions, the error changed to:

>ERROR: purchasePackageFailed(error:) purchasePackage failed: Error Domain=RCPurchasesErrorDomain Code=2 "There was a problem with the App Store." UserInfo={readable_error_code=STORE_PROBLEM, NSLocalizedDescription=There was a problem with the App Store., NSUnderlyingError=0x282fd5fe0 {Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x282fc45a0 {Error Domain=ASDErrorDomain Code=500 "Unhandled exception" UserInfo={NSUnderlyingError=0x282fc4660 {Error Domain=AMSErrorDomain Code=203 "Bag Load Failed" UserInfo=0x2834ac3c0 (not displayed)}, NSLocalizedFailureReason=An unknown error occurred, NSLocalizedDescription=Unhandled exception}}}}}

**Comment by rkotzy** [comment]
I'm able to repro this as well. The error messages being returned are from Apple, before any connection is made to RevenueCat. When the purchase is initiated, the SDK does not check for an active network connection first, it fires off the request to Apple as soon as possible. 

The NETWORK_ERROR from the SDK is returned when there's a network connection issue to the RevenueCat API - so if you went in airplane mode at the split second after the purchase completed, but before it was sent to RevenueCat, you should get a NETWORK_ERROR.

Apple doesn't have a documented SKError for network issue we could map too. There _may_ be a way to do it with the `NSURLErrorDomain`, but this doesn't seem to be documented in the context of StoreKit and if it changes between tests it wouldn't be a reliable error to return anyway. 

RevenueCat _could_ try to detect a network connection before sending the purchase attempt to Apple, but blocking a purchase is always something we try to avoid. 

Hope this helps clear things up!
