### ISSUE TITLE
Carthage currently not working

### ISSUE THREAD

**Issue by RiverbayChris** [RevenueCat/purchases-ios#40]
Running Carthage update produces the below, but nothing is actually downloaded:

*** Downloading purchases-ios.framework binary at "1.0.4"

**Comment by jeiting** [comment]
Which version of Carthage are you on?

**Comment by RiverbayChris** [comment]
Fixed by using this cartfile entry instead:

github "revenuecat/purchases-ios" "release/1.0.4"
