### ISSUE TITLE
Feature Request: Show Current Plan on Subscription Templates

### ISSUE THREAD

**Issue by rocxteady** [RevenueCat/purchases-ios#4105]
Hi guys,

First of all; didn't want to use the feature request contact page since I wanted opinions about this.

I wanted to see the current subscription plan that the user has. I couldn't find a way to show it with the latest version. Isn't there such a function?

I modified the source dode a little bit and I come up with these screen inspired by Apple's own implementation. It's just a quick implementation. 

First screen show's when the currently subscribed plan is not selected. It only says "_**Current Plan**_" and the user can continue with other plans. The second image shows a disabled state of the button because you can't subscribe to the plan you already have.

What are your opinions? What can be improved? Right now "_**Current Plan**_" text  and _**disabled background color of the continue button**_ is hard coded. And the "_**Current Plan**_" text getting its color from the current tier's color.

![Simulator Screenshot - iPhone 15 Pro - 2024-07-24 at 14 40 29](https://github.com/user-attachments/assets/556e864f-2b32-4d6f-b8a3-1d5f35f0e312)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-24 at 14 44 42](https://github.com/user-attachments/assets/cae7a4cd-8e43-4630-a1da-69817f70db22)

**Comment by nyeu** [comment]
Hi @rocxteady,

Thank you for your feedback. I've forwarded your request to the team, and they will prioritize it accordingly.
I'll go ahead and close this issue since it is product related. Feel free to reopen it if you have any concern.
