### ISSUE TITLE
RevenueCatUI missing from RevenueCat.xcframework?

### ISSUE THREAD

**Issue by hansemannn** [RevenueCat/purchases-ios#4168]
Is it expected that RevenueCatUI is missing from the RevenueCat.xcframework? We are using RevenueCat for a long time and very extensively, but haven't seen a way to use this one so far. It's also not built via Carthage, so it's kind of a blocker for us, as we need a pre-packaged version of it.

Thanks in advance!

**Comment by aboedo** [comment]
We don't have a pre-built xcframework for it, we'd have to vend it separately. 

Let me see if I can set that up quickly

**Comment by aboedo** [comment]
It wasn't quick 😅 but the XCFramework is now officially a part of releases 🎉  so I'll tentatively mark this one as closed. Feel free to reopen if needed!

**Comment by aboedo** [comment]
It wasn't quick 😅 but the XCFramework is now officially a part of releases 🎉  so I'll tentatively mark this one as closed. Feel free to reopen if needed!

**Comment by hansemannn** [comment]
@aboedo There seemed to be a signing issue with the attached binary, but I'll try a later release to see if it changes something. Just curious to see if that's a known issue atm.

<img width="683" alt="Screenshot 2024-09-06 at 9 37 57 PM" src="https://github.com/user-attachments/assets/6df53c56-d442-4830-b62d-a8351b16e458">
