### ISSUE TITLE
Latest SDK fails to build on macOS

### ISSUE THREAD

**Issue by hebertialmeida** [RevenueCat/purchases-ios#424]
**Describe the bug**
I'm integrating RC in my macOS app and the latest version of the SDK (3.9.1) fails to build after integrated, that seems to happen after the version 3.8.0 that added `presentCodeRedemptionSheet`. The version 3.7.6 builds normally.

1. Environment
    1. Platform: macOS
    2. SDK version: 3.9.1
    3. OS version: 10.15.7
    4. Xcode version: 12.1

3. Steps to reproduce
Install the SDK via SPM on a macOS app (AppKit not Catalyst) and build the project, that will fail.

**Additional context**
File: RCStoreKitWrapper.m

Screenshot:
![Screen Shot 2020-12-17 at 9 58 25 AM](https://user-images.githubusercontent.com/103670/102504126-70db9e80-404e-11eb-973f-d60a7e4f2334.png)

**Comment by aboedo** [comment]
confirmed on Xcode 12.0. 
This has been fixed in #185, and will be a part of the 3.9.2 release, coming out very soon (#423)

**Comment by aboedo** [comment]
@hebertialmeida thanks for reporting!!

**Comment by hebertialmeida** [comment]
Thanks!

**Comment by aboedo** [comment]
3.9.2 is out now with the fix! @hebertialmeida let me know if you run into any more issues. Closing this issue now.
