### ISSUE TITLE
Wrong bundle short version generation

### ISSUE THREAD

**Issue by serbancoroiu** [RevenueCat/purchases-ios#447]
I have added RevenueCat framework in my project using Carthage and the `CFBundleShortVersionString` is generated wrong: 

![image](https://user-images.githubusercontent.com/48278459/104581503-56a1da00-5667-11eb-96ef-6499f69ad418.png)

When i am trying to deploy the app on Apple iTunes i am receiving an error message because the `CFBundleShortVersionString` should be a list of at most 3 non-negative integers. Check the error message below. 

![image](https://user-images.githubusercontent.com/48278459/104581820-c6b06000-5667-11eb-9e23-987b94c161e7.png)

Environment

Platform: iOS
SDK version: 3.8.0
OS version: 10.15.7
Xcode version: 12.3

**Comment by aboedo** [comment]
Hi! 👋 Thanks for reporting. I've updated the carthage 3.8.0 release so it should be fixed. Let us know if you run into any more issues!
