### ISSUE TITLE
Manual integration?

### ISSUE THREAD

**Issue by agrinman** [RevenueCat/purchases-ios#47]
It would be great if we could add this as a dependency just using `git submodules` if we are not using Carthage or Cocoapods.

**Comment by jeiting** [comment]
Yeah, that's totally doable. Just add a submodule and manually adding the project as a sub-project should work™️. Let me know if it doesn't.

**Comment by agrinman** [comment]
Apologies for the delay, finally got around to debugging further...that's what I tried at first, but it wasn't quite working like it usually does for other framework-project deps. 

FWIW Here's what worked for me:
1. add as a submodule
2. drag the entire `purchases-ios` folder into your project (do **not** add to your app target)
3. add framework as you usually do (you'll see purchases.framework)
