### ISSUE TITLE
RCPurchases.sharedPurchases can be nil, but not marked as nullable

### ISSUE THREAD

**Issue by smokyfire** [RevenueCat/purchases-ios#490]
I'm proposing that
`@property (class, nonatomic, readonly) RCPurchases *sharedPurchases;`
should be
`@property (class, nonatomic, readonly, nullable) RCPurchases *sharedPurchases;`

to reflect the correct nullability to the Swift compiler. This is useful for example when some Swift code wants to assert that `Purchases` has been configured properly. 

If you agree with this, I am happy to open a PR.

**Comment by smokyfire** [comment]
Sounds good 👍 Thank you!

**Comment by aboedo** [comment]
Update here: [the fix](https://github.com/RevenueCat/purchases-ios/pull/508) has been merged and will be released in the next update! Thanks again @smokyfire for pointing this out!
