### ISSUE TITLE
Creating Alias debug log is backwards.

### ISSUE THREAD

**Issue by danthorpe** [RevenueCat/purchases-ios#497]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

This debug log is backwards:

https://github.com/RevenueCat/purchases-ios/blob/194ec49a4dfded1c1884a8c0867cdf7dc336bad6/Purchases/Identity/RCIdentityManager.m#L81

The `creating_alias` is defined as `to %@ from %@`

https://github.com/RevenueCat/purchases-ios/blob/194ec49a4dfded1c1884a8c0867cdf7dc336bad6/PurchasesCoreSwift/Logging/Strings/IdentityStrings.swift#L25

So, this means that the order of the arguments should be _new user id_ and then _old user id_. Currently it's the wrong way round. Needless to say, this is very confusing, when trying to understand what RevenueCat is doing.

1. Environment
   1. Platform: iOS
   2. SDK version: 3.11.0
   3. OS version: All
   4. Xcode version: All
   5. How widespread is the issue. Percentage of devices affected. All
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
    ```
    [Purchases] - DEBUG: 👤 Identifying from an anonymous ID: $RCAnonymousID:3d962b76173341909b70983c8047042b. An alias will be created.
    [Purchases] - DEBUG: 👤 Creating an alias to $RCAnonymousID:3d962b76173341909b70983c8047042b from <REDACTED>
    ```
3. Steps to reproduce, with a description of expected vs. actual behavior
    1. Follow the documentation to set up RevenueCat, in the case where you fetch the user Id from your own systems
    2. Then sign in.
    3. Read debug logs, which indicate that the alias is in the wrong direction.
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by vegaro** [comment]
Yes, that's a pretty confusing log. Thanks for bringing this up. I will open a quick PR to update it

**Comment by vegaro** [comment]
Just merged https://github.com/RevenueCat/purchases-ios/pull/498. It will go out with the next release. Closing this.
