### ISSUE TITLE
Non-String Subscriber Attributes Crashes App

### ISSUE THREAD

**Issue by ralphcode** [RevenueCat/purchases-ios#499]
**Describe the bug**

When setting attributes if a numeric value is provided, the value is saved to `UserDefaults` as an `NSNumber`  I.e.
```
Purchases.setAttributes({
     cbid: projUser.id   // = 14050
});
```

When called a second time the `storeAttributeLocallyIfNeededWithKey` method loads the `NSNumber` value but compares it as an `NSString` using `isEqualToString`, which crashes the device. 
```
- (void)storeAttributeLocallyIfNeededWithKey:(NSString *)key
                                       value:(nullable NSString *)value
                                   appUserID:(NSString *)appUserID {
    NSString *valueOrEmpty = value ?: @"";
    NSString *_Nullable currentValue = [self currentValueForAttributeWithKey:key appUserID:appUserID];
    if (!currentValue || ![currentValue isEqualToString:valueOrEmpty]) {      // <!-- Here
        [self storeAttributeLocallyWithKey:key value:valueOrEmpty appUserID:appUserID];
    }
}
```

The app then needs to be deleted, before it can ever be used again as this occurs every time the app loads (as we set this value while loading our user objects).

<img width="1000" alt="Screen Shot 2021-04-24 at 2 59 11 pm" src="https://user-images.githubusercontent.com/24926020/115947820-b54fdd00-a50d-11eb-87cc-2385cb772002.png">

If the intention is to only support string values (which is fine by us), then I'd suggest either casting all inputs as a string before saving or, throwing an error so we know this is not allowed while developing.

We are now casting everything as a string before calling `setAttributes` but someone else might trip over this like we did;

```
Purchases.setAttributes({
     cbid: projUser.id + ''   // = "14050"
});
```

Thanks! 👍 

- [ x ] I have updated Purchases SDK to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/develop/CONTRIBUTING.md)
- [ x ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ x ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

1. Environment
   1. Platform: iOS
   2. SDK version: Latest
   3. OS version: 14.5
   4. Xcode version: 10.15.7 (19H2)
   5. How widespread is the issue. Percentage of devices affected: All
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Comment by aboedo** [comment]
Hi! 👋  Thanks for opening. 

Our API does specify that the input type of that method is supposed to be: 
`NSDictionary <NSString *, NSString *> *` in Objective-C, and 
`[String: String]` in Swift

https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases/Public/RCPurchases.h#L414

And in fact, if you attempt to send a non-string in Objective-C, you get a build warning: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3922667/116150357-a443cf00-a6b9-11eb-860a-f002d506286c.png">

And in Swift you get a compilation error:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/3922667/116150426-bde51680-a6b9-11eb-96c5-baee43ae8038.png">

However, these are Lightweight Generics in Objective-C, and depending on how you're sending over the values, the compiler might not catch the issue. 

Could you shed some light on how you came across the issue? Was this while using `purchases-ios` directly, or through one of our plugins? (i.e. React-Native, Flutter, Cordova, Unity, etc)
If so, we might be able to improve our APIs on those to make sure that non-string values won't be passed in

**Comment by Ralpharoo** [comment]
Hi @aboedo 

Sorry, I should have specified. The bug/crashes occurs within `purchase-ios` however, this is made possible through the Cordova plugin `cordova-plugin-purchases` (and maybe other non-typed ones).

To replicate, you can run this in JavaScript with the Cordova plugin installed;

```
document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
    Purchases.setDebugLogsEnabled(true);
    Purchases.setup("public_sdk_key");
    Purchases.setAttributes({
         test: 1234
    });
}
```

This will then crash `purchase-ios` per the original post.

Do you want me to move this over to the Cordova repo? It could be bulletproofed from both the JavaScript (to force a string value, or throw an error) but also dynamic type checking in Objective-C.

Cheers,

**Comment by aboedo** [comment]
@Ralpharoo that makes sense. 
Yeah, I think we should enforce types in both sides, for the sake of having a better crash log at least. 

We do have the type documented in `cordova-plugin-purchases` as `{ [key: string]: string | null }` in [typescript](https://github.com/RevenueCat/cordova-plugin-purchases/blob/develop/src/plugin/plugin.ts#L928), but that [won't translate over to javascript](https://github.com/RevenueCat/cordova-plugin-purchases/blob/develop/www/plugin.js#L420) unfortunately.
