### ISSUE TITLE
[Purchases] - Cached appUserID has been deleted from user defaults

### ISSUE THREAD

**Issue by norrisboat** [RevenueCat/purchases-ios#518]
- [ x ] I have updated Purchases SDK to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/develop/CONTRIBUTING.md)
- [ x  ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [  x ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [  x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
My app crashes on a new install or when I log out with this error message.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[Purchases] - Cached appUserID has been deleted from user defaults. This leaves the SDK in an undetermined state. Please make sure that RevenueCat entries in user defaults don't get deleted by anything other than the SDK. More info: https://support.revenuecat.com/hc/en-us/articles/360047927393'

1. Environment
   1. Platform: iOS
   2. SDK version: 3.11.1
   3. OS version: 14.4.2
   4. Xcode version: 12.5 (12E262)
   5. How widespread is the issue. Percentage of devices affected: All beta users after integration
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
* Fresh install of app with Revenue cat integration

**Comment by beylmk** [comment]
Hi @norrisboat thanks for opening an issue! Can you please confirm for me whether you're making any calls to clear user defaults from your app? 

Also - can you please share any calls to the RevenueCat SDK upon logout and on application startup?

**Comment by norrisboat** [comment]
@beylmk when a user logs out from my app I clear user defaults.

```swift
        let domain = Bundle.main.bundleIdentifier!
        UserDefaults.standard.removePersistentDomain(forName: domain)
        UserDefaults.standard.synchronize()
```

**Comment by norrisboat** [comment]
@beylmk your comment lead me to find that I was actually supposed to use

```swift
Purchases.configure(withAPIKey: key, appUserID: userID, observerMode: true, userDefaults: UserDefaults(suiteName: "userDefaultsForRevenuecat"))
```

After doing that it works just fine.
