### ISSUE TITLE
Migrate FoundationExtension

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#540]
Migrating the whole FoundationExtension folder:
The extensions are rather small, and they are used internally.

There will be 1 challenge- the NSError extension. It references:
```objc
#import "RCPurchasesErrors.h"
#import "RCBackend.h"
```

- `RCPurchasesErrors` contains enums
- `RCBackend` contains a couple const strings that are referenced.
- 

So, 2 approaches

1. you could migrate both those imports
2. you could decline to migrate NSError until somebody else migrates those two files.

**Comment by joshdholtz** [comment]
@taquitos The last issue I tackled for #542 was for a single class. The one looks like it's for an entire folder, correct? Can we maybe get a description update for the specific classes/files that this issue all includes? 😇 Are there also any known gotchas that this issue could cause? Thank you! ❤️

**Comment by taquitos** [comment]
Yooo, yeah, sorry, I meant to go back and flesh this out a little more.
You're right! It's for the entire folder 🙀

**Comment by joshdholtz** [comment]
@taquitos No worries 😊 Appreciate the quick response!

**Comment by joshdholtz** [comment]
Also... I can't assign myself but I got this one 💪

**Comment by joshdholtz** [comment]
@taquitos If we could create a new/separate issue for the `NSError+RCExtensions.m` that would be 🔥  That one is a little more work and different than the rest and I think it deserves it's own issue and PR 😊

**Comment by taquitos** [comment]
![YouGotItDude](https://user-images.githubusercontent.com/1304821/123714909-18bafb80-d82c-11eb-9fd9-cd5b7928896e.gif)
https://github.com/RevenueCat/purchases-ios/issues/604

**Comment by joshdholtz** [comment]
@taquitos Thank you!! PR incoming for this one then 😊 And your gif game is still strong 🙌

**Comment by taquitos** [comment]
💪
