### ISSUE TITLE
Migrate RCAttributionFetcher

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#572]
Blocked on
- [x] #538 
- [x] #577 
- [ ] #575
- [x] #573

**Comment by vegaro** [comment]
I can take care of this once https://github.com/RevenueCat/purchases-ios/pull/609 is merged since it's blocked by it

**Comment by vegaro** [comment]
Removed dependency from RCBackend since it's actually not using it, it's only passed to the constructor and not used.
