### ISSUE TITLE
SwiftLint complains about not being installed on CI for two of the 3 targets

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#621]
Let's update the linter script to not run swiftlint if we have a certain environment variable set. 
That way we don't need to touch the pre-commit script or script phase in Xcode.
We'll still need to update CircleCI config to set the environment variable for the jobs we don't want to use swift lint in.

**Comment by vegaro** [comment]
Was this supposed to be closed? @taquitos

**Comment by taquitos** [comment]
Whoops, I forgot to close it, thank you stale bot 😄
