### ISSUE TITLE
New build step that checks for things that we might get caught up on

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#629]
Grep for "TARGET_OS" in swift files and return an error since that means we're seeing ` #if TARGET_OS` and that won't work in Swift, but will still compile 🤦‍♂️

**Comment by Juanpe** [comment]
Hi!

I could do this, but I don't understand very well what this issue means. 😕 The idea is that there aren't available classes on some platforms, and we aren't checking it or checking wrongly? 🤔 

BTW, the target test doesn't support all the platforms, only `iOS`. I think it'd make sense to support the rest, wouldn't it?

**Comment by Juanpe** [comment]
Good idea 👍🏼 

I could do both or at least one of them 🙂 Which one is more priority?

**Comment by Juanpe** [comment]
Hi @taquitos, I've opened a PR with a proposal for the build step. 

Let me know if you think it's enough to fix the problem :)
