### ISSUE TITLE
purchaserInfo.purchaseDate(forProductIdentifier returns a null purchase date for a purchased renewing product

### ISSUE THREAD

**Issue by leisurehound** [RevenueCat/purchases-ios#64]
Here is some sample client code that demonstrates the issue

        for purchasedProductIdentifier in purchaserInfo.allPurchasedProductIdentifiers {
            
            print ("ID: \(purchasedProductIdentifier)")
            print("Start Date:  \(String(describing: purchaserInfo.purchaseDate(forProductIdentifier: purchasedProductIdentifier)))")
            print("End Date:  \(String(describing: purchaserInfo.expirationDate(forProductIdentifier: purchasedProductIdentifier)))")
        }

For renewing products, the purchase date is always nil.

**Comment by leisurehound** [comment]
Will purchaseDate be supported?  Was this fixed separately?

**Comment by rkotzy** [comment]
Re-opening this. Will require a server change to fix but can use this issue as a status tracker.

**Comment by rkotzy** [comment]
This is working now for the SDK and API.
