### ISSUE TITLE
Expose master appUserID to clients to support non-renewing products restoration across devices

### ISSUE THREAD

**Issue by leisurehound** [RevenueCat/purchases-ios#65]
Since RevenueCat does not fully support non-renewing subscriptions (restoration across devices, storing expiration dates, etc) I am working around this by storing the information in Firebase.  However, I need to tie together purchases made in one device to another device of the same user for restoration.  

Initially I tried to use RCPurchases.appUserID to do so but learned that they are unique to the device, not the appleID user, when using anonymous auth. 

My app has no need for login/authorization beyond purchasing products and my users have spoken loudly they don't want a monthly subscription to the app.  So non-renewing products are critical.

One solution I have is to expose the master user ID in the RevenueCat backend in RCPurchases or in RCPurchaserInfo.  It is my understanding that this is the primary key for joining the list of device userAppIDs. This would give me a 1:1 relationship to the appleID I need to restore non-renewing transactions from Firebase.  I think this would be a reasonable stopgap until RevenueCat fully supports non-renewing products.

I am open to other ideas to handle this too, this is simply the best one I thought of.  In the end, solving the restoration and storing of supplemental information is the primary goal ahead of RevenueCat fully supporting non-renewing products.  Ideally, if this could be exposed by Dec 15, 2018 that would align best with the 'season' picking up for my customers.

**Comment by rkotzy** [comment]
Closing this as an issue since it's more of a feature request. I've added it to the public roadmap here: [https://trello.com/c/I8GkwCYn](https://trello.com/c/I8GkwCYn)
