### ISSUE TITLE
Promoted in-app purchase doesn't work

### ISSUE THREAD

**Issue by rizwan95** [RevenueCat/purchases-ios#651]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

Implementation of shouldPurchasePromoProduct doesn't work properly. When a promoted in-app purchase is tapped, nothing happens. It would be great if a sample code is provided for shouldPurchasePromoProduct. I have seen the documentations but it is of not much help. Please give us a sample implementation in the sample app. 

1. Environment
   1. Platform: iOS 
   2. SDK version: 3.11.1
   3. OS version: iOS 14
   4. Xcode version: Xcode 12.5
   5. How widespread is the issue. Percentage of devices affected. - Almost all devices 
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue - No
3. Steps to reproduce, with a description of expected vs. actual behavior

Implement ```shouldPurchasePromoProduct``` delegate method. Tap a promoted in-app purchase from the appstore or try to simulate one using the itms-service link

Expected behaviour:
The app should open and it should buy the product

Actual behaviour:
The app just opens and nothing happens.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Related stackoverflow question:
https://stackoverflow.com/questions/67851573/swift-promoted-products-with-revenuecat-caching-the-defermentblock

**Comment by vegaro** [comment]
I just tried it out and it looks like I got it to work fine.

**Make sure you set are setting `Purchases.shared.delegate = self` after calling configure and not before** (someone had that issue [here](https://docs.revenuecat.com/discuss/5d715b81cd94cb004ded6542)).

Then implement the delegate function like:

```swift
func purchases(_ purchases: Purchases, shouldPurchasePromoProduct product: SKProduct, defermentBlock makeDeferredPurchase: @escaping RCDeferredPromotionalPurchaseBlock) {
    makeDeferredPurchase { (transaction, info, error, cancelled) in
        if let purchaserInfo = info {
            handlePurchaserInfo()
        }
    }
}    
```

With caching the defermentBlock we mean that you can save the deferment block as a property of your object and then call it whenever your app is ready to make the purchase. So you could do something like:

```swift
    var maybeDeferredPurchase: RCDeferredPromotionalPurchaseBlock? = nil
    
    func purchases(_ purchases: Purchases, shouldPurchasePromoProduct product: SKProduct, defermentBlock makeDeferredPurchase: @escaping RCDeferredPromotionalPurchaseBlock) {
        maybeDeferredPurchase = makeDeferredPurchase
    }
```

And then, whenever you want to show the purchase pop-up (like when the screen has loaded for example) do:

```swift
if let defermentBlock = self.maybeDeferredPurchase {
    defermentBlock { (transaction, info, error, cancelled) in
        if let purchaserInfo = info {
            handlePurchaserInfo()
        }
    }
}
```

To test it works, you can open a link like `itms-services://?action=purchaseIntent&bundleId=<YOUR_BUNDLE_ID>&productIdentifier=<YOUR_SKPRODUCT_ID>` in your device. For example, in my tester app it was `itms-services://?action=purchaseIntent&bundleId=com.revenuecat.sampleapp&productIdentifier=com.revenuecat.lifetime.199.99`.

Let me know if that helps

**Comment by rizwan95** [comment]
Thank you so much for the detailed response! I will test it out and let you know!
