### ISSUE TITLE
Calling `setDebugLogsEnabled(false)` enables debug logs when it should not

### ISSUE THREAD

**Issue by dams229** [RevenueCat/purchases-ios#662]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
The method `setDebugLogsEnabled` has been deprecated since version 3.12.0, but it's behavior has been altered: calling `setDebugLogsEnabled(false)` has the opposite effect because in the code:
```
+ (void)setDebugLogsEnabled:(BOOL)enabled {
    [self setLogLevel:RCLogLevelDebug];
}
```
Level is always set to __debug__.

Could you fix it or completely remove the method to avoid any error?
Thank you

1. Environment
   1. Platform: iOS
   2. SDK version: 3.12.1
   3. OS version: All
   4. Xcode version: All
   5. How widespread is the issue. Percentage of devices affected. 100%

**Comment by aboedo** [comment]
hi! thanks for reporting! I'll make a fix. Sorry for the inconvenience!

**Comment by dams229** [comment]
Not a big issue, thank you!

**Comment by aboedo** [comment]
bug fix PR is up! https://github.com/RevenueCat/purchases-ios/pull/663

Will merge and make a new release as soon as it gets approved. 

Thanks again for reporting!! 🎉

**Comment by aboedo** [comment]
Release 3.12.2 is out with the fix! 🎉 Closing this now, but let us know if you run into any issues!
