### ISSUE TITLE
Create dictionary merging extension with default uniquingKeysWith parameter

### ISSUE THREAD

**Issue by beylmk** [RevenueCat/purchases-ios#678]
see conversation here: https://github.com/RevenueCat/purchases-ios/pull/674

**Comment by Juanpe** [comment]
Hi @beylmk! I've created a PR with a proposal for this issue. Please, let me know what do you think about it 🙂

**Comment by beylmk** [comment]
> Hi @beylmk! I've created a PR with a proposal for this issue. Please, let me know what do you think about it 🙂

Hey @Juanpe awesome 😍 Checking it out now!
