### ISSUE TITLE
Move platform checks away from `RCPurchases.m`

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#687]
We have a few platform checks that live in `RCPurchases.m`, that can be moved away from it into a more relevant place. 
In particular, the ones that decide which notification is the `ApplicationDidBecomeActiveNotification`. 

see #680 for details

**Comment by Juanpe** [comment]
Hi! is this issue ready to be closed? Maybe I could use `Closes issue` instead of `Resolves issue` to close the issues when the PR is merged 🤔

**Comment by aboedo** [comment]
yep! I'll close it out.
For a lot of PRs I usually do `Addresses issue x` so that it won't auto-close, but I only do that so that issues don't get closed before I actually ship out a release version with the changes. 
For the swift migration project, we won't be able to ship out a release version until everything is done, so it makes sense to have them auto-close when each PR is merged.
