### ISSUE TITLE
Pull logs from RCPurchases into relevant classes

### ISSUE THREAD

**Issue by beylmk** [RevenueCat/purchases-ios#688]
See notes in RCPurchases

**Comment by taquitos** [comment]
Am I being dense? I don't see notes, could you point me in the right direction?

**Comment by beylmk** [comment]
it's the `// todo: move log to relevant class` ones! basically just pulling the RCLogs out so we further enforce RCPurchases being just the entry point (if that makes sense...)

you're not dense, perhaps it just seems like a very minor thing to be making a ticket for...

**Comment by taquitos** [comment]
Ahhh that makes sense. It's good to have the ticket 😄

**Comment by aboedo** [comment]
closed via #719
