### ISSUE TITLE
create new `OfferingsManager` class

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#691]
See #680 for details. 

We have some logic in `RCPurchases.m` to fetch offerings, handle backend responses, cache, etc. We should move it into its own class. 

### Blockers
- [x] #581

**Comment by Juanpe** [comment]
This issue looks appealing to me, If it's still available, I could do it 🙂

**Comment by aboedo** [comment]
hey @Juanpe 👋 ! Thanks for offering!! 
This is still available, but it's currently blocked by #581, I forgot to add that to the description. You can take it as soon as that one is done!

**Comment by Juanpe** [comment]
Ah ok ok! 👍🏼

**Comment by Juanpe** [comment]
Hi! since the Backend was migrated I've created a PR that includes the new `OfferingsManager` class.
