### ISSUE TITLE
move logic to `SKPaymentTransaction` extension

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#693]
See #680 for details. 

We have some logic that currently lives in `RCPurchases`, but could be an `SKPaymentTransaction` extension instead.

**Comment by Juanpe** [comment]
I checked the code but I've a question related to this issue 🤔 

This is the code:
```objective-c
// todo: move to SKPaymentTransaction Extension
- (nullable NSString *)productIdentifierFrom:(SKPaymentTransaction *)transaction {
    if (transaction.payment == nil) {
        [RCLog appleWarning:[NSString stringWithFormat:@"%@",
                             RCStrings.purchase.skpayment_missing_from_skpaymenttransaction]];
    } else if (transaction.payment.productIdentifier == nil) {
        [RCLog appleWarning:[NSString stringWithFormat:@"%@",
                             RCStrings.purchase.skpayment_missing_product_identifier]];
    }
    return transaction.payment.productIdentifier;
}
```

Since neither the [`payment`](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411286-payment) nor the [`productIdentifier`](https://developer.apple.com/documentation/storekit/skpayment/1506155-productidentifier) is optional, why are we validating them? Are there any strange scenarios where they could be `nil`?

**Comment by aboedo** [comment]
yeah, app store quirks mostly. We've seen it happen a few times. 
when moving it to swift, I think the compiler might not even let us check against `nil`, not sure what's a good way around that. 
Perhaps the issues have been solved, so there's a chance that this isn't even necessary anymore, but I'm not 100% sure about it.

**Comment by aboedo** [comment]
since the compiler will probably complain, perhaps we could start by not doing the checks, but adding a note or comment about it, and then we can do a round of as thorough testing as possible before we ship the migrated swift version of the sdk

**Comment by Juanpe** [comment]
Checking the git logs, I saw that this code was introduced to solve issue #279, so I think we must continue validating the nullability. If we create an optional copy of the transaction, the compiler will allow us to check if the payment is nil or not. 

I'm going to create a PR with this solution and let me know if it looks good for you 👍🏼

**Comment by aboedo** [comment]
awesome, thanks so much!! 💪
