### ISSUE TITLE
simplify `HTTPClient` logic

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#694]
`HTTPClient` currently exposes a single `performRequest` method, which takes in the `method` and the `body`, and then performs assertions to make sure that gets aren't called with a body and posts are called with a body, and that requests always use one of those two `method`s. 

This could be simplified by just having two separate method signatures for get and post.

**Comment by Juanpe** [comment]
I could split it :)

**Comment by aboedo** [comment]
all yours!! thanks @Juanpe!!

**Comment by aboedo** [comment]
fixed via #697
