### ISSUE TITLE
Investigate writing a script that can help people migrate

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#738]
I think we'll need to experiment with packaging up our Swift-based SDK, and then dropping it in an app that is already using the OG RC SDK, document all the breakages and then we can figure out the best way to help migrate folks.

- [x] confirm APITester fully tests old API
- [x] create list of all breaking changes
- [x] create plan for script to automate updates

**Comment by aboedo** [comment]
done!
