### ISSUE TITLE
Replace expectToThrowException and expectToNotThrowException

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#759]
These were used for objc->swift exception bridging with ARM64. We no longer need them and can go back to using Nimble for non-arm. Most of these methods that throw exceptions/assert should probably raise errors instead, that's a lot friendlier for us, but also it enables us to have consistent tests on arm64 instead of having to hack together different solutions.

**Comment by vegaro** [comment]
I moved these in https://github.com/RevenueCat/purchases-ios/pull/764 and moved the bridging header for them to work. I think it would be better to replace them in another PR what do you think?

**Comment by taquitos** [comment]
Yeah, totally. Thank you!
