### ISSUE TITLE
activeProduct is nil

### ISSUE THREAD

**Issue by nyeu** [RevenueCat/purchases-ios#77]
Hi,
I am just integrating RevenueCat for subscriptions and when I try to do a purhcase, `activeProduct` is nil. According to the documentation:
> The active product, this will be null if the product is not available, usually because it has not been approved for sale

This is correct, my product in iTunesConnect is still not `Ready for Sale`, but how can I test this? I want to call `self.purchases.makePurchase(product)`.

Am I missing anything? Did I understood it wrong?

I use Xcode 10.0 and an iPhone X with iOS 12.

Thank you

**Comment by jeiting** [comment]
Hey!

Make sure you do everything in this post to get your product "Ready for Sale" or "Ready to Submit"
https://www.revenuecat.com/2018/10/11/configuring-in-app-products-is-hard

**Comment by nyeu** [comment]
Hey,
Thanks for the response. I'm closing the ticket as my issue was answered in the blog post.
