### ISSUE TITLE
Switch api to use precondition(_:_:file:line:) instead of an assert()

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#771]
https://github.com/RevenueCat/purchases-ios/blob/3541071eeed94e1673c2ec44c33820931c5e89e5/PurchasesCoreSwift/Networking/Backend.swift#L639

https://github.com/RevenueCat/purchases-ios/blob/swift_migration/PurchasesCoreSwift/Networking/Backend.swift#L648

**Comment by NachoSoto** [comment]
See conversation in #1069, marked as wontfix.
