### ISSUE TITLE
Refactor EntitlementInfo to use Codable

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#774]
We pull from dictionaries: 
```swift
entitlementData: [String: Any],
productData: [String: Any],
```

We should migrate this over to Codable

**Comment by Juanpe** [comment]
Hi @taquitos 👋🏼 Could you provide more details about it? I mean, these dictionaries coming from the `SubscriberData` object, which is created in the `PurchaseInfo` constructor, so the idea is to modify all these elements or just decode this `entitlementData` and `productData` using Codable. Do you know what I mean? 🤔
