### ISSUE TITLE
Add support for SK2 discounts

### ISSUE THREAD

**Issue by vegaro** [RevenueCat/purchases-ios#848]
- [x] Add support for SK2 with discounts and intro prices
~~- [ ] Move discount logic from Purchases to a new class~~ -> Moved to #1055
- [x] Update PurchaseTester's SwiftPaywall to display intro prices for SK2 products

**Comment by aboedo** [comment]
tracked in Shortcut as https://app.shortcut.com/revenuecat/story/7665/promo-offers-in-sk2

**Comment by NachoSoto** [comment]
I've done the first and last task. @vegaro can you provide some context on what you mean by "Move discount logic from Purchases to a new class"? Which logic exactly? 🙏

**Comment by vegaro** [comment]
@NachoSoto That task was extracted from this TODO https://github.com/RevenueCat/purchases-ios/pull/800/files#diff-3abb303d85fe43612dbf8b92aa8d6a79a622070fde888ca7c8c2f4cfed0128e8R907

But I think I misunderstood and what needed to be move to a new class was the purchase logic not the discount logic. So I think that can be considered done since it's already in PurchasesOrchestrator. @aboedo wrote the TODO so maybe he knows different

**Comment by aboedo** [comment]
well, the thinking is to have _some_ place handle: 
- deciding whether to use SK1 or SK2 for the purchase
- apply the discounts (if needed). 

Purchases.swift should be as thin and light as possible

**Comment by NachoSoto** [comment]
> Purchases.swift should be as thin and light as possible

Totally agreed. I'm not super familiar with the nearly-1600 lines of code in there :P could you point out what logic in there we should move out? I'll file a separate ticket for that since it seems like it's not fully related to this one.

**Comment by aboedo** [comment]
haha sure! 
The line mostly refers to the following two things happening in Purchases.swift: 
- [setting up a `payment` and starting a purchase with the `payment`](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Public/Purchases.swift#L944)
- [determining which SK version to use for a given `StoreProduct`, then creating a `payment` for it](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Public/Purchases.swift#L996).

We'll have to have different logic for both SK versions, and we'll eventually want to also add support for the `quantity` field in `SKPayment` (and its equivalent for SK2), so moving those responsibilities into a different class will make things easier to maintain in the long run

**Comment by NachoSoto** [comment]
Cool thanks! I filed #1055 for that so we can call this issue finished.
