### ISSUE TITLE
RevenueCat Runtime Error on watchOS

### ISSUE THREAD

**Issue by Yrban** [RevenueCat/purchases-ios#860]
I use the same class to implement RevenueCat in an iOS & watchOS app.  I get a runtime error when running the simulator for any watch running watchOS 8:
"runtime: SwiftUI: Accessing State's value outside of being installed on a View. This will result in a constant Binding of the initial value and will not update."

The breakpoints show the problem in this section of RevenueCat:

```
private extension ReceiptFetcher {

    func receiptData() -> Data? {
        guard var receiptURL: URL = receiptBundle.appStoreReceiptURL else {
            Logger.debug(Strings.receipt.no_sandbox_receipt_restore)
            return nil
        }

        #if os(watchOS)
        // as of watchOS 6.2.8, there's a bug where the receipt is stored in the sandbox receipt location,
        // but the appStoreReceiptURL method returns the URL for the production receipt.
        // This code replaces "sandboxReceipt" with "receipt" as the last component of the receiptURL so that we get the
        // correct receipt.
        // This has been filed as radar FB7699277. More info in https://github.com/RevenueCat/purchases-ios/issues/207.

        let firstOSVersionWithoutBug: OperatingSystemVersion = OperatingSystemVersion(majorVersion: 7,
                                                                                      minorVersion: 0,
                                                                                      patchVersion: 0)
        let isBelowFirstOSVersionWithoutBug = ProcessInfo.processInfo.isOperatingSystemAtLeast(firstOSVersionWithoutBug)

        if isBelowFirstOSVersionWithoutBug && SystemInfo.isSandbox {
            let receiptURLFolder: URL = receiptURL.deletingLastPathComponent()
            let productionReceiptURL: URL = receiptURLFolder.appendingPathComponent("receipt")
            receiptURL = productionReceiptURL
        }
        #endif

        guard let data: Data = try? Data(contentsOf: receiptURL) else {
            Logger.debug(Strings.receipt.unable_to_load_receipt)
            return nil
        }

        Logger.debug(Strings.receipt.loaded_receipt(url: receiptURL))

        return data
    }

```

The breakpoint is at the guard statement. I was not having this in the prior package. I have not deployed for testing yet, as I have some more things to deal with before TestFlight. This error is watchOS only, and does not affect iOS builds.

**Comment by taquitos** [comment]
Heya @Yrban, we haven't had a chance to dig into this yet, but I came across this post that may/may not be relevant to you. 
https://stackoverflow.com/questions/62633728/accessing-viewmodel-field-in-swiftui-using-xcode-12-accessing-states-value-ou
The [accepted solution](https://stackoverflow.com/a/62633945/2237910) suggests there might be something you can try out in your code while we take a look at this.

**Comment by Yrban** [comment]
This error pops up prior to getting to any view. It hits somewhere after I configure Purchases and attempt to restore purchases in the ExtensionDelegate.

**Comment by Yrban** [comment]
This may not be your issue. I reverted to the last release of Purchases, and the error is showing up in a different place. When I comment that place out, I get it in yet a different place. It seems to be an issue with watchOS on Xcode13RC. I am still investigating that.

**Comment by taquitos** [comment]
Let us know if you still think this is something we need to investigate 😁
