### ISSUE TITLE
Update tests with forced unwrapping to use XCTUnwrap

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#881]
We use force unwrapping in our tests, we should update them all to use `XCTUnwrap` so that the tests don't crash/stop at the first instance of nil.

Some extra context if needed: https://github.com/RevenueCat/purchases-ios/pull/879#discussion_r718678007

**Comment by NachoSoto** [comment]
Done in #969.
There could still be some places missing though.
