### ISSUE TITLE
Missing nullability annotations in `RCPurchaserInfo+Protected.h`

### ISSUE THREAD

**Issue by davedelong** [RevenueCat/purchases-ios#89]
I'm getting a bunch of "missing nullability annotation" warnings in RCPurchaserInfo+Protected.h.

I'm not sure what the annotations should be, or I'd probably do it myself. I like my projects to build cleanly without warnings.

**Comment by vegaro** [comment]
Hey @davedelong thanks for reporting. It looks like these warnings started appearing with the new Xcode. We will make sure they don't show up in `2.1.0` stable version.

**Comment by vegaro** [comment]
https://github.com/RevenueCat/purchases-ios/releases/tag/2.1.0 should fix this
