### ISSUE TITLE
Please leave old API in place, but mark it as unavailable or deprecated

### ISSUE THREAD

**Issue by davedelong** [RevenueCat/purchases-ios#90]
I just updated my copy of Purchases to the latest version, and got hit with a bunch of compiler errors about missing methods or missing parameters.

Next time you add parameters, leave the old method in place but mark it as deprecated, and add the hint to use a different on instead.

Instead of removing methods, remove their _implementations_, and then mark the method in the header as deprecated, and point to the new method.

This helps make upgrading from release to release much easier for users.

**Comment by vegaro** [comment]
Thanks for opening this @davedelong and sorry we broke the compilation that time. We took notes of your recommendations and are actively working on avoiding this type of situation.

I am going to close this issue to keep things tidy in the repo if that's fine. 

Cheers!
