### ISSUE TITLE
Is the API of Version 4 stable?

### ISSUE THREAD

**Issue by thisisthekap** [RevenueCat/purchases-ios#928]
I am the maintainer of https://github.com/thisisthekap/Xamarin.RevenueCat.iOS, and I am looking forward to updating the bindings to RevenueCat SDK version 4.

I am considering to start working on this binding update even though RevenueCat SDK version 4 is still considered beta.

To begin working on the binding update, I need confirmation, the the API surface of RevenueCat SDK version 4 is considered as stable.

**Comment by codykerns** [comment]
Hey @thisisthekap!

As v4 is still in beta, it's very likely that things may continue to change. At this point, I wouldn't consider the surface to be stable and you'll probably want to hold off for now.
