### ISSUE TITLE
Add info about using for macOS + minimum requirements

### ISSUE THREAD

**Issue by tunabelly** [RevenueCat/purchases-ios#93]
I honestly thought this repo was just for iOS and then found out it supports macOS as well. This is great since I'm going to be using it for Mac apps. 

I believe it would be helpful to mention this in the readme as well as the minimum version of macOS needed, which seems to be 10.12.

And thanks for supporting both iOS and macOS, it's a nice change to see!

**Comment by rkotzy** [comment]
Clarifying this in the readme here: https://github.com/RevenueCat/purchases-ios/pull/98

Also calling it out better in our online documentation with a dedicated navigation link: https://docs.revenuecat.com/docs/macos

**Comment by guruz** [comment]
10.12+ actually seems wrong to me, I'm on 10.13 but the following enums are 10.14+
```
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:157:18: error: use of undeclared identifier 'SKErrorPrivacyAcknowledgementRequired'
            case SKErrorPrivacyAcknowledgementRequired:
                 ^
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:162:18: error: use of undeclared identifier 'SKErrorUnauthorizedRequestData'
            case SKErrorUnauthorizedRequestData:
                 ^
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:163:18: error: use of undeclared identifier 'SKErrorMissingOfferParams'
            case SKErrorMissingOfferParams:
                 ^
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:164:18: error: use of undeclared identifier 'SKErrorInvalidOfferPrice'
            case SKErrorInvalidOfferPrice:
                 ^
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:165:18: error: use of undeclared identifier 'SKErrorInvalidSignature'; did you mean 'errSecInvalidSignature'?
            case SKErrorInvalidSignature:
                 ^~~~~~~~~~~~~~~~~~~~~~~
                 errSecInvalidSignature
In module 'Foundation' imported from /Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrors.h:9:
In module 'Security' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:477:5: note: 'errSecInvalidSignature' declared here
    errSecInvalidSignature                   = -67688,    /* An invalid signature was encountered. */
    ^
/Users/guruz/.../Pods/Purchases/Purchases/Public/RCPurchasesErrorUtils.m:166:18: error: use of undeclared identifier 'SKErrorInvalidOfferIdentifier'
            case SKErrorInvalidOfferIdentifier:
```
This was only added recently in https://github.com/RevenueCat/purchases-ios/commit/5e52bde95f9e340b4f0cb9cced7aa888c3b92faf

However I understand that this is about developer machine (having latest Apple enums) vs target machine, if I would update my macOS it would magically fix this.

Do you plan to fix this? Maybe not..

**Comment by rkotzy** [comment]
Hey @guruz. Yeah 10.12+ is the min version you can target, I see how that could be unclear. This should help clarify: https://github.com/RevenueCat/purchases-ios/pull/99

We need to require the latest XCode version sometimes so the newest `StoreKit` APIs are available.

**Comment by tunabelly** [comment]
@rkotzy thanks for taking care of this one!
