### ISSUE TITLE
Indicate user cancelled in restoreTransactions API

### ISSUE THREAD

**Issue by hiltonc** [RevenueCat/purchases-ios#94]
When I call restoreTransactions I'm prompted for my app store password. If I tap cancel, I would expect an error or other indication of cancellation, but my completion is called with success.

I would like to know if the operation is cancelled so that I can know whether to show a "purchases restored" alert.

**Comment by jeiting** [comment]
I'm assuming this is in Sandbox. We see a lot of strange behaviors in Sandbox.

It might be the case that the receipt gets refreshed even though you hit cancel. 

What version of iOS are you using and what's your Sandbox account set up?

**Comment by hiltonc** [comment]
Yes, Sandbox. This is on iOS 12.2. I've installed the app via TestFlight.

**Comment by rkotzy** [comment]
The latest release should prevent the password prompt from displaying every time -> https://github.com/RevenueCat/purchases-ios/releases/tag/2.1.1 

Just to clarify, the success / failure callbacks aren't indications that the user restored purchases, just that the `PurchaserInfo` was successfully updated with the device receipt. You should still check if the user has a specific active subscription or entitlement in the success block.
