### ISSUE TITLE
reset() is deprecated but logout() does not reset anonymous users

### ISSUE THREAD

**Issue by weakfl** [RevenueCat/purchases-ios#941]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

I'm trying to `invalidatePurchaserInfoCache()` and `reset()` user id during unit tests.
The `Purchases.shared.reset()` function is marked deprecated, however, the `Purchases.shared.logOut()` function does not reset anonymous users:

https://github.com/RevenueCat/purchases-ios/blob/3d5835da2ab03866a9e2609b91d4e0b056afa50c/Purchases/Identity/IdentityManager.swift#L87-L98

**Comment by JazmineMT** [comment]
Hi @weakfl ,

Happy to help out here! Could you send debug logs that reproduce this? You can enable debug logs by following this guide. After they're enabled you'll see logs like this in the console:


```
[Purchases] - DEBUG: No cached entitlements, fetching
[Purchases] - DEBUG: GET /v1/subscribers/<APP_USER_ID> 200
[Purchases] - DEBUG: Purchaser info updated, sending to delegate
```

Please ensure the debug logs include the entire app life-cycle, including the messages printed during initialization of the SDK. The more information you include here, the better we'll be able to help.



Let me know if you have any questions!

**Comment by weakfl** [comment]
@JazmineMT I'm not sure what's happening, but if I don't call `Purchases.shared.reset()` on teardown, I still get a `Purchases.EntitlementInfo` containing a purchase on subsequent launch:

```
Optional("<RCEntitlementInfo: identifier=<removed>,\nisActive=1,\nwillRenew=0,\nperiodType=0,\nlatestPurchaseDate=2021-11-12 06:58:31 +0000,\noriginalPurchaseDate=2021-11-12 06:58:31 +0000,\nexpirationDate=(null),\nstore=0,\nproductIdentifier=<removed>,\nisSandbox=1,\nunsubscribeDetectedAt=(null),\nbillingIssueDetectedAt=(null),\nownershipType=0,\n>")
```

If I do call `Purchases.shared.reset()` on teardown the `Purchases.EntitlementInfo` is `nil` on subsequent launch.

**Comment by JazmineMT** [comment]
Hey @weakfl, 

I haven't been able to reproduce this issue. Can you send over the debug logs that reproduce this? Both when you call Purchases.shared.reset() on teardown and when you do not.  This will help get a full picture of what's going on in your setup.

Thanks!

**Comment by weakfl** [comment]
@JazmineMT teardown logs are identical.

The only difference, without `Purchases.shared.reset()` the device cache is not cleared and on subsequent launch the entitlement is restored.

With `reset()` in teardown `- (void)clearCachesForAppUserID:(NSString *)oldAppUserID andSaveNewUserID:(NSString *)newUserID` gets called, device cache is cleared and the entitlement is empty on subsequent launch.

**Comment by JazmineMT** [comment]
Hi @weakfl , 

Thank you for being patient while I looked into this issue. I believe the issue is being caused because NSUserDefaults are being saved between test runs. We use that as cache storage, and it’s not cleared between runs automatically. You would need to use a specific suiteName when setting up and pass that instance of userDefaults when configuring, then clear them in the teardown.

```
override func setUp() {
   let userDefaults = UserDefaults(suiteName: "TestDefaults")
   let purchases = Purchases.configure(withAPIKey: "xxxxx", appUserID: nil, observerMode: false, userDefaults: userDefaults)
}

override func tearDown() {
   UserDefaults().removePersistentDomain(forName: "TestDefaults")
} 
```

Let us know if this solves your issue!

**Comment by weakfl** [comment]
@JazmineMT Thanks, that approach works.
