### ISSUE TITLE
MockETagManager is not thread safe, which results in random test failures

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#945]
This likely only happens when running tests in parallel. Here's the stack trace:
![Screen Shot 2021-11-15 at 14 21 04](https://user-images.githubusercontent.com/685609/141862083-f9d7fd62-5870-4ce8-9985-7137343da3d2.png)

And the race condition is here:
![Screen Shot 2021-11-15 at 14 21 47](https://user-images.githubusercontent.com/685609/141862163-92aaaa93-a728-4d5c-96c7-76c1be888210.png)

Because `HTTPClient` uses `ETagManager` from a background thread. I see that `ETagManager` itself uses an `NSRecursiveLock`, but `MockETagManager` isn't thread safe.

**Comment by taquitos** [comment]
Nice catch, flaky tests are the worst.
