### ISSUE TITLE
[fastlane] no output or number of passed/failed tests in scan because XCPretty doesn't work with parallelization 

### ISSUE THREAD

**Issue by joshdholtz** [RevenueCat/purchases-ios#971]
## Background
I'm working on removing _fastlane_'s dependency on XCPretty when running `scan`. XCPretty will still be an option for formatting but `scan` won't _need_ it to run.

Project 👉 https://github.com/fastlane/fastlane/projects/4
Draft PR 👉 https://github.com/fastlane/fastlane/pull/19629

I was looking for an open source project that used `scan` and `trainer` to test my changes against and this one seemed to be a good fit 😊 

## Something I noticed
When trying out some of my changes, I noticed that the `test` lane the scan configuration had the following options set:

```
output_types: ''
```

My guess here is that because the tests are using parallelization that XCPretty was causing issues in the tests. `scan` currently uses the XCPretty junit output to determine the number of tests the passed and failed but... XCPretty doesn't work with parallelization enabled.

It seems like setting `output_types` and `fail_build` might have been ways to get around this (but please let me know if I'm wrong 😛)

❗ So even though `scan` is working, its not showing number of passed and failed tests until the `trainer` report is completed

## Future changes to be made
Once the _fastlane_ [project for removing XCPretty](Project 👉 https://github.com/fastlane/fastlane/projects/4) is complete and https://github.com/fastlane/fastlane/pull/19629 is merged, I would like to:

- Update to newest version of `fastlane`
  - This will show number of passed and failed tests in `scan` summary
- Change `scan`  and `gym to use `xcbeautify`
  - This requires `xcbeautify` to be installed (usually through `brew install xcbeautify1)
  - This will show better build and test output that works with parallelization enabled

**Comment by joshdholtz** [comment]
👇 This is what `scan` output will look like when using `xcbeautify`


https://user-images.githubusercontent.com/401294/142562814-ab5368f7-3e69-4676-b611-99b50568af6e.mov

**Comment by NachoSoto** [comment]
😍 😍 😍 
XCPretty is so 2014.

**Comment by joshdholtz** [comment]
Not stale! I promise 😁

**Comment by aboedo** [comment]
still not stale, bot!

**Comment by aboedo** [comment]
adding the `enhancement` label to make sure the bot doesn't mark it again
