### ISSUE TITLE
No such module 'RevenueCat' using SPM with latest beta 4.0.0-beta.7

### ISSUE THREAD

**Issue by alpennec** [RevenueCat/purchases-ios#986]
I wanted to give the latest beta (version 7) a try but I can't make it work.
I'm using SPM in my project. It's correctly fetched by Xcode (showing the Purchases dependency) but I can't import it in my app.(I'm using the commit version because otherwise it fetches the 6th beta).

Have I missed anything?

Thanks.
Axel

<img width="489" alt="image" src="https://user-images.githubusercontent.com/2082662/143058962-5afbf816-eb36-4448-bc77-d213f5f71e6a.png">

<img width="252" alt="image" src="https://user-images.githubusercontent.com/2082662/143058875-37fbbf46-4253-437a-867b-b1e67296a9ea.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/2082662/143058828-4d1759eb-b856-4ab8-9b4c-b68092a8811c.png">

**Comment by taquitos** [comment]
Give this a try- 

- Start fresh by removing the package entirely.
- Pin to the exact beta 7 version:
![Screen Shot 2021-11-23 at 9 20 51 AM](https://user-images.githubusercontent.com/1304821/143073046-82f4f80a-f840-40ea-a614-d9da99935449.png)

When asked to choose package products for the framework, make sure it's checked:
![Screen Shot 2021-11-23 at 9 25 00 AM](https://user-images.githubusercontent.com/1304821/143073757-f1234b54-c8c5-48fe-8663-c7d776c84f7a.png)

**Comment by alpennec** [comment]
Thanks, it worked!
