### ISSUE TITLE
fix: IDFV/guuid for macOS

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#991]
We use the guuid when validating receipts generated using `StoreKitTest` (i.e.: when using [StoreKit Configuration files](https://docs.revenuecat.com/docs/apple-app-store#ios-14-only-testing-on-the-simulator)). 

The receipts generated with this format can't be validated against Apple's servers, so we have to do the validation ourselves. 
However, in order to validate the receipts, we need to get a device identifier. 

For iOS, watchOS and tvOS, this identifier is the `idfv`. 

However, for macOS, getting the value is more complicated. 
The documentation for computing the value in macOS is available in the section titled "Compute the SHA-1 Hash" here:
https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device

The goal is to update this [method in SystemInfo](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Misc/SystemInfo.swift#L84) to return the correct values as specified above, for macOS and mac Catalyst targets. 

https://app.shortcut.com/revenuecat/story/7921/mac-catalyst-storekit-configuration-receipts-failing-to-be-validated

**Comment by Juanpe** [comment]
Hi!!👋🏼 I would like to try to solve this issue. Is it already assigned?

**Comment by aboedo** [comment]
all yours! Will take a look at the PR, thanks so much @Juanpe!
